-- =====================================================
-- Family Tree Platform - PostgreSQL Database Schema
-- =====================================================
-- For Integration with Baseline Application
-- ASP.NET Identity with UINT (INTEGER) User IDs
-- PostgreSQL 16+ with Full-Text Search (tsvector, pg_trgm)
-- =====================================================

-- Enable required PostgreSQL extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- =====================================================
-- 1. ASP.NET IDENTITY TABLES (Already in Your Baseline)
-- =====================================================
-- NOTE: Your baseline already has these tables with INTEGER IDs
-- This is included for reference only - DO NOT create again

/*
CREATE TABLE "AspNetUsers" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserName" VARCHAR(256),
    "NormalizedUserName" VARCHAR(256),
    "Email" VARCHAR(256),
    "NormalizedEmail" VARCHAR(256),
    "EmailConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
    "PasswordHash" TEXT,
    "SecurityStamp" TEXT,
    "ConcurrencyStamp" TEXT,
    "PhoneNumber" TEXT,
    "PhoneNumberConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
    "TwoFactorEnabled" BOOLEAN NOT NULL DEFAULT FALSE,
    "LockoutEnd" TIMESTAMP WITH TIME ZONE,
    "LockoutEnabled" BOOLEAN NOT NULL DEFAULT FALSE,
    "AccessFailedCount" INTEGER NOT NULL DEFAULT 0
);
*/

-- =====================================================
-- 2. ORGANIZATIONS TABLE
-- =====================================================
CREATE TABLE "Orgs" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "Name" VARCHAR(200) NOT NULL,
    "SettingsJson" JSONB,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX "IX_Orgs_Name" ON "Orgs" ("Name");

-- =====================================================
-- 3. ORG-USER JUNCTION TABLE (Multi-Tenant)
-- =====================================================
-- IMPORTANT: UserId is INTEGER to match AspNetUsers in your baseline
CREATE TABLE "OrgUsers" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "OrgId" UUID NOT NULL,
    "UserId" INTEGER NOT NULL,  -- ✅ INTEGER for uint (matches your baseline)
    "Role" INTEGER NOT NULL DEFAULT 0, -- 0=Viewer, 1=Contributor, 2=Editor, 3=Admin, 4=Owner
    "JoinedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_OrgUsers_Orgs" FOREIGN KEY ("OrgId") 
        REFERENCES "Orgs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrgUsers_AspNetUsers" FOREIGN KEY ("UserId") 
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_OrgUsers_OrgId_UserId" ON "OrgUsers" ("OrgId", "UserId");

-- =====================================================
-- 4. PLACES TABLE
-- =====================================================
CREATE TABLE "Places" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "OrgId" UUID NOT NULL,
    "Name" VARCHAR(200) NOT NULL,
    "Type" VARCHAR(50),
    "ParentId" UUID,
    "Latitude" DOUBLE PRECISION,
    "Longitude" DOUBLE PRECISION,
    "AltNamesJson" JSONB,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_Places_Orgs" FOREIGN KEY ("OrgId") 
        REFERENCES "Orgs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Places_ParentPlace" FOREIGN KEY ("ParentId") 
        REFERENCES "Places" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Places_OrgId_Name" ON "Places" ("OrgId", "Name");
CREATE INDEX "IX_Places_ParentId" ON "Places" ("ParentId");

-- =====================================================
-- 5. PEOPLE TABLE (Core Genealogy Entity)
-- =====================================================
CREATE TABLE "People" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "OrgId" UUID NOT NULL,
    "PrimaryName" VARCHAR(200),
    "Sex" INTEGER NOT NULL DEFAULT 2, -- 0=Male, 1=Female, 2=Unknown
    "Gender" VARCHAR(50),
    
    -- Birth Information
    "BirthDate" TIMESTAMP,
    "BirthPrecision" INTEGER NOT NULL DEFAULT 5, -- 0=Exact, 1=About, 2=Between, 3=Before, 4=After, 5=Unknown
    "BirthPlaceId" UUID,
    
    -- Death Information
    "DeathDate" TIMESTAMP,
    "DeathPrecision" INTEGER NOT NULL DEFAULT 5,
    "DeathPlaceId" UUID,
    
    -- Additional Info
    "PrivacyLevel" INTEGER NOT NULL DEFAULT 1, -- 0=Public, 1=FamilyOnly, 2=Private, 3=InitialsOnly
    "Occupation" TEXT,
    "Education" TEXT,
    "Religion" TEXT,
    "Nationality" TEXT,
    "Ethnicity" TEXT,
    "Notes" TEXT,
    
    -- Full-Text Search Vector (Generated Column)
    "SearchVector" TSVECTOR GENERATED ALWAYS AS (
        to_tsvector('english', 
            COALESCE("PrimaryName", '') || ' ' || 
            COALESCE("Occupation", '') || ' ' || 
            COALESCE("Notes", '')
        )
    ) STORED,
    
    -- Metadata Flags
    "IsVerified" BOOLEAN NOT NULL DEFAULT FALSE,
    "NeedsReview" BOOLEAN NOT NULL DEFAULT FALSE,
    "HasConflict" BOOLEAN NOT NULL DEFAULT FALSE,
    
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_People_Orgs" FOREIGN KEY ("OrgId") 
        REFERENCES "Orgs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_People_BirthPlace" FOREIGN KEY ("BirthPlaceId") 
        REFERENCES "Places" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_People_DeathPlace" FOREIGN KEY ("DeathPlaceId") 
        REFERENCES "Places" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_People_OrgId" ON "People" ("OrgId");
CREATE INDEX "IX_People_PrimaryName" ON "People" ("PrimaryName");
CREATE INDEX "IX_People_SearchVector" ON "People" USING GIN ("SearchVector");

-- =====================================================
-- 6. PERSON NAMES TABLE (Multi-Script Support)
-- =====================================================
CREATE TABLE "PersonNames" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "PersonId" UUID NOT NULL,
    "Script" VARCHAR(10) NOT NULL DEFAULT 'Latin', -- Latin, Arabic, Nobiin
    "Given" VARCHAR(100),
    "Middle" VARCHAR(100),
    "Family" VARCHAR(100),
    "Full" VARCHAR(300),
    "Transliteration" VARCHAR(300),
    "Type" INTEGER NOT NULL DEFAULT 0, -- 0=Primary, 1=Alias, 2=Maiden, 3=Nickname, 4=Tribal, 5=Clan
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_PersonNames_People" FOREIGN KEY ("PersonId") 
        REFERENCES "People" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_PersonNames_PersonId" ON "PersonNames" ("PersonId");
CREATE INDEX "IX_PersonNames_Full" ON "PersonNames" USING GIN ("Full" gin_trgm_ops);
CREATE INDEX "IX_PersonNames_Given" ON "PersonNames" USING GIN ("Given" gin_trgm_ops);
CREATE INDEX "IX_PersonNames_Family" ON "PersonNames" USING GIN ("Family" gin_trgm_ops);

-- =====================================================
-- 7. UNIONS TABLE (Marriages/Partnerships)
-- =====================================================
CREATE TABLE "Unions" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "OrgId" UUID NOT NULL,
    "Type" INTEGER NOT NULL DEFAULT 0, -- 0=Marriage, 1=CivilUnion, 2=Partnership, 3=CommonLaw
    
    -- Start Information
    "StartDate" TIMESTAMP,
    "StartPrecision" INTEGER NOT NULL DEFAULT 5,
    "StartPlaceId" UUID,
    
    -- End Information (Divorce/Separation)
    "EndDate" TIMESTAMP,
    "EndPrecision" INTEGER NOT NULL DEFAULT 5,
    "EndPlaceId" UUID,
    
    "Notes" TEXT,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_Unions_StartPlace" FOREIGN KEY ("StartPlaceId") 
        REFERENCES "Places" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Unions_EndPlace" FOREIGN KEY ("EndPlaceId") 
        REFERENCES "Places" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_Unions_OrgId" ON "Unions" ("OrgId");

-- =====================================================
-- 8. UNION MEMBERS TABLE (Supports Polygamy)
-- =====================================================
CREATE TABLE "UnionMembers" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "UnionId" UUID NOT NULL,
    "PersonId" UUID NOT NULL,
    "Role" VARCHAR(50) NOT NULL DEFAULT 'Spouse',
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_UnionMembers_Unions" FOREIGN KEY ("UnionId") 
        REFERENCES "Unions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UnionMembers_People" FOREIGN KEY ("PersonId") 
        REFERENCES "People" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_UnionMembers_UnionId_PersonId" ON "UnionMembers" ("UnionId", "PersonId");

-- =====================================================
-- 9. PARENT-CHILD RELATIONSHIPS TABLE
-- =====================================================
CREATE TABLE "ParentChildren" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "ParentId" UUID NOT NULL,
    "ChildId" UUID NOT NULL,
    "RelationshipType" INTEGER NOT NULL DEFAULT 0, -- 0=Biological, 1=Adoptive, 2=Step, 3=Foster, 4=Guardian
    "Certainty" VARCHAR(50),
    "Notes" TEXT,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_ParentChildren_Parent" FOREIGN KEY ("ParentId") 
        REFERENCES "People" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ParentChildren_Child" FOREIGN KEY ("ChildId") 
        REFERENCES "People" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_ParentChildren_ParentId" ON "ParentChildren" ("ParentId");
CREATE INDEX "IX_ParentChildren_ChildId" ON "ParentChildren" ("ChildId");
CREATE UNIQUE INDEX "IX_ParentChildren_ParentId_ChildId_Type" 
    ON "ParentChildren" ("ParentId", "ChildId", "RelationshipType");

-- =====================================================
-- 10. MEDIA FILES TABLE
-- =====================================================
CREATE TABLE "MediaFiles" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "OrgId" UUID NOT NULL,
    "Url" VARCHAR(500) NOT NULL,
    "StorageKey" VARCHAR(500) NOT NULL,
    "Kind" INTEGER NOT NULL DEFAULT 0, -- 0=Image, 1=Video, 2=Audio, 3=Document
    "Title" VARCHAR(200),
    "Description" TEXT,
    "CaptureDate" TIMESTAMP,
    "CapturePlaceId" UUID,
    "Visibility" INTEGER NOT NULL DEFAULT 1, -- 0=Public, 1=FamilyOnly, 2=Private
    "Copyright" TEXT,
    "MetadataJson" JSONB,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_MediaFiles_Orgs" FOREIGN KEY ("OrgId") 
        REFERENCES "Orgs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MediaFiles_CapturePlace" FOREIGN KEY ("CapturePlaceId") 
        REFERENCES "Places" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_MediaFiles_OrgId" ON "MediaFiles" ("OrgId");
CREATE INDEX "IX_MediaFiles_StorageKey" ON "MediaFiles" ("StorageKey");

-- =====================================================
-- 11. SOURCES TABLE
-- =====================================================
CREATE TABLE "Sources" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "OrgId" UUID NOT NULL,
    "Title" VARCHAR(300) NOT NULL,
    "Repository" VARCHAR(200),
    "Citation" TEXT,
    "Url" VARCHAR(500),
    "MetadataJson" JSONB,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX "IX_Sources_OrgId" ON "Sources" ("OrgId");
CREATE INDEX "IX_Sources_Title" ON "Sources" ("Title");

-- =====================================================
-- 12. TAGS TABLE
-- =====================================================
CREATE TABLE "Tags" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "OrgId" UUID NOT NULL,
    "Name" VARCHAR(100) NOT NULL,
    "Color" VARCHAR(50),
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE UNIQUE INDEX "IX_Tags_OrgId_Name" ON "Tags" ("OrgId", "Name");

-- =====================================================
-- 13. PERSON-TAG JUNCTION TABLE
-- =====================================================
CREATE TABLE "PersonTags" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "PersonId" UUID NOT NULL,
    "TagId" UUID NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_PersonTags_People" FOREIGN KEY ("PersonId") 
        REFERENCES "People" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PersonTags_Tags" FOREIGN KEY ("TagId") 
        REFERENCES "Tags" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_PersonTags_PersonId_TagId" ON "PersonTags" ("PersonId", "TagId");

-- =====================================================
-- 14. AUDIT LOG TABLE
-- =====================================================
-- IMPORTANT: ActorId is INTEGER to match AspNetUsers in your baseline
CREATE TABLE "AuditLogs" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "ActorId" INTEGER NOT NULL,  -- ✅ INTEGER for uint (matches your baseline)
    "EntityType" VARCHAR(100) NOT NULL,
    "EntityId" UUID NOT NULL,
    "Action" VARCHAR(50) NOT NULL,
    "ChangeJson" JSONB,
    "Timestamp" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_AuditLogs_AspNetUsers" FOREIGN KEY ("ActorId") 
        REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_AuditLogs_ActorId" ON "AuditLogs" ("ActorId");
CREATE INDEX "IX_AuditLogs_EntityType_EntityId" ON "AuditLogs" ("EntityType", "EntityId");
CREATE INDEX "IX_AuditLogs_Timestamp" ON "AuditLogs" ("Timestamp");

-- =====================================================
-- SEED DATA
-- =====================================================

-- Create default organization
INSERT INTO "Orgs" ("Id", "Name", "SettingsJson", "CreatedAt", "UpdatedAt")
VALUES (
    uuid_generate_v4(),
    'Smith Family Tree',
    '{"defaultLanguage":"en","supportedLanguages":["en","ar","nob"]}'::jsonb,
    NOW() AT TIME ZONE 'UTC',
    NOW() AT TIME ZONE 'UTC'
);

-- =====================================================
-- COMMENTS & NOTES
-- =====================================================

COMMENT ON TABLE "AspNetUsers" IS 'ASP.NET Identity users with INTEGER primary keys (uint32)';
COMMENT ON TABLE "OrgUsers" IS 'Multi-tenant org membership - UserId references AspNetUsers (INTEGER)';
COMMENT ON TABLE "AuditLogs" IS 'Audit trail - ActorId references AspNetUsers (INTEGER)';
COMMENT ON TABLE "People" IS 'Core genealogy entity with multi-tenant support';
COMMENT ON COLUMN "People"."SearchVector" IS 'Auto-generated tsvector for full-text search';
COMMENT ON TABLE "PersonNames" IS 'Supports multi-script names (Latin, Arabic, Nobiin)';
COMMENT ON TABLE "UnionMembers" IS 'Junction table supporting polygamy (multiple spouses per union)';
COMMENT ON TABLE "ParentChildren" IS 'Parent-child relationships with cycle detection logic in application';

-- =====================================================
-- INTEGRATION NOTES
-- =====================================================
/*
This schema integrates with your existing baseline application:

1. User ID Type: INTEGER (uint32) to match your AspNetUsers
2. Foreign Keys: OrgUsers.UserId and AuditLogs.ActorId use INTEGER
3. Database: FamilyTree (same as your existing connection string)
4. Identity Tables: Already exist in your baseline - DO NOT recreate

Key Changes from Standalone Version:
- User IDs: BIGINT → INTEGER
- User Model: ApplicationUser → AspNetUser (your existing model)
- JWT Config: Use your existing comprehensive setup
- Storage: Use your existing IStorageService factory

To Integrate:
1. Run this SQL script to create Family Tree tables
2. Add Family Tree entities to your ApplicationDbContext
3. Update OrgUser and AuditLog models to use uint
4. Run EF Core migration
5. Test with your existing JWT authentication
*/

-- =====================================================
-- SUMMARY
-- =====================================================
-- Total Tables: 14 Family Tree + Your Existing Identity Tables
-- Multi-Tenant: Yes (OrgId on all entities)
-- Full-Text Search: tsvector with pg_trgm
-- Indexes: 35+ (GIN, B-Tree, Unique)
-- User ID Type: INTEGER (uint32) for baseline compatibility
-- =====================================================
