-- =====================================================
-- Family Tree Platform - PostgreSQL Database Schema
-- =====================================================
-- .NET 8 Web API with Entity Framework Core 8 + ASP.NET Identity
-- PostgreSQL 16+ with Full-Text Search (tsvector, pg_trgm)
-- Updated: November 2025 - ASP.NET Identity Migration
-- =====================================================

-- Enable required PostgreSQL extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- =====================================================
-- 1. ASP.NET IDENTITY TABLES (Managed by Identity Framework)
-- =====================================================
-- NOTE: These tables are created automatically by Entity Framework Core
-- when using ASP.NET Identity. Included here for reference.

CREATE TABLE "AspNetRoles" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(256),
    "NormalizedName" VARCHAR(256),
    "ConcurrencyStamp" TEXT
);

CREATE TABLE "AspNetUsers" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserName" VARCHAR(256),
    "NormalizedUserName" VARCHAR(256),
    "Email" VARCHAR(256),
    "NormalizedEmail" VARCHAR(256),
    "EmailConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
    "PasswordHash" TEXT,
    "SecurityStamp" TEXT,
    "ConcurrencyStamp" TEXT,
    "PhoneNumber" TEXT,
    "PhoneNumberConfirmed" BOOLEAN NOT NULL DEFAULT FALSE,
    "TwoFactorEnabled" BOOLEAN NOT NULL DEFAULT FALSE,
    "LockoutEnd" TIMESTAMP WITH TIME ZONE,
    "LockoutEnabled" BOOLEAN NOT NULL DEFAULT FALSE,
    "AccessFailedCount" INTEGER NOT NULL DEFAULT 0,
    
    -- Custom Properties
    "FirstName" VARCHAR(100),
    "LastName" VARCHAR(100),
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "LastLoginAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" BIGINT NOT NULL,
    "RoleId" BIGINT NOT NULL,
    PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers" FOREIGN KEY ("UserId") 
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles" FOREIGN KEY ("RoleId") 
        REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" SERIAL PRIMARY KEY,
    "UserId" BIGINT NOT NULL,
    "ClaimType" TEXT,
    "ClaimValue" TEXT,
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers" FOREIGN KEY ("UserId") 
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" VARCHAR(128) NOT NULL,
    "ProviderKey" VARCHAR(128) NOT NULL,
    "ProviderDisplayName" TEXT,
    "UserId" BIGINT NOT NULL,
    PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers" FOREIGN KEY ("UserId") 
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" BIGINT NOT NULL,
    "LoginProvider" VARCHAR(128) NOT NULL,
    "Name" VARCHAR(128) NOT NULL,
    "Value" TEXT,
    PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers" FOREIGN KEY ("UserId") 
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" SERIAL PRIMARY KEY,
    "RoleId" BIGINT NOT NULL,
    "ClaimType" TEXT,
    "ClaimValue" TEXT,
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles" FOREIGN KEY ("RoleId") 
        REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

-- Identity Indexes
CREATE UNIQUE INDEX "IX_AspNetRoles_NormalizedName" ON "AspNetRoles" ("NormalizedName");
CREATE UNIQUE INDEX "IX_AspNetUsers_NormalizedUserName" ON "AspNetUsers" ("NormalizedUserName");
CREATE UNIQUE INDEX "IX_AspNetUsers_NormalizedEmail" ON "AspNetUsers" ("NormalizedEmail");
CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

-- =====================================================
-- 2. ORGANIZATIONS TABLE
-- =====================================================
CREATE TABLE "Orgs" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "Name" VARCHAR(200) NOT NULL,
    "SettingsJson" JSONB,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX "IX_Orgs_Name" ON "Orgs" ("Name");

-- =====================================================
-- 3. ORG-USER JUNCTION TABLE (Multi-Tenant)
-- =====================================================
-- UPDATED: UserId changed from UUID to BIGINT to match AspNetUsers
CREATE TABLE "OrgUsers" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "OrgId" UUID NOT NULL,
    "UserId" BIGINT NOT NULL,
    "Role" INTEGER NOT NULL DEFAULT 0, -- 0=Viewer, 1=Contributor, 2=Editor, 3=Admin, 4=Owner
    "JoinedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_OrgUsers_Orgs" FOREIGN KEY ("OrgId") 
        REFERENCES "Orgs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrgUsers_AspNetUsers" FOREIGN KEY ("UserId") 
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_OrgUsers_OrgId_UserId" ON "OrgUsers" ("OrgId", "UserId");

-- =====================================================
-- 4. PLACES TABLE
-- =====================================================
CREATE TABLE "Places" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "OrgId" UUID NOT NULL,
    "Name" VARCHAR(200) NOT NULL,
    "Type" VARCHAR(50),
    "ParentId" UUID,
    "Latitude" DOUBLE PRECISION,
    "Longitude" DOUBLE PRECISION,
    "AltNamesJson" JSONB,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_Places_Orgs" FOREIGN KEY ("OrgId") 
        REFERENCES "Orgs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Places_ParentPlace" FOREIGN KEY ("ParentId") 
        REFERENCES "Places" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Places_OrgId_Name" ON "Places" ("OrgId", "Name");
CREATE INDEX "IX_Places_ParentId" ON "Places" ("ParentId");

-- =====================================================
-- 5. PEOPLE TABLE (Core Genealogy Entity)
-- =====================================================
CREATE TABLE "People" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "OrgId" UUID NOT NULL,
    "PrimaryName" VARCHAR(200),
    "Sex" INTEGER NOT NULL DEFAULT 2, -- 0=Male, 1=Female, 2=Unknown
    "Gender" VARCHAR(50),
    
    -- Birth Information
    "BirthDate" TIMESTAMP,
    "BirthPrecision" INTEGER NOT NULL DEFAULT 5, -- 0=Exact, 1=About, 2=Between, 3=Before, 4=After, 5=Unknown
    "BirthPlaceId" UUID,
    
    -- Death Information
    "DeathDate" TIMESTAMP,
    "DeathPrecision" INTEGER NOT NULL DEFAULT 5,
    "DeathPlaceId" UUID,
    
    -- Additional Info
    "PrivacyLevel" INTEGER NOT NULL DEFAULT 1, -- 0=Public, 1=FamilyOnly, 2=Private, 3=InitialsOnly
    "Occupation" TEXT,
    "Education" TEXT,
    "Religion" TEXT,
    "Nationality" TEXT,
    "Ethnicity" TEXT,
    "Notes" TEXT,
    
    -- Full-Text Search Vector (Generated Column)
    "SearchVector" TSVECTOR GENERATED ALWAYS AS (
        to_tsvector('english', 
            COALESCE("PrimaryName", '') || ' ' || 
            COALESCE("Occupation", '') || ' ' || 
            COALESCE("Notes", '')
        )
    ) STORED,
    
    -- Metadata Flags
    "IsVerified" BOOLEAN NOT NULL DEFAULT FALSE,
    "NeedsReview" BOOLEAN NOT NULL DEFAULT FALSE,
    "HasConflict" BOOLEAN NOT NULL DEFAULT FALSE,
    
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_People_Orgs" FOREIGN KEY ("OrgId") 
        REFERENCES "Orgs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_People_BirthPlace" FOREIGN KEY ("BirthPlaceId") 
        REFERENCES "Places" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_People_DeathPlace" FOREIGN KEY ("DeathPlaceId") 
        REFERENCES "Places" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_People_OrgId" ON "People" ("OrgId");
CREATE INDEX "IX_People_PrimaryName" ON "People" ("PrimaryName");
CREATE INDEX "IX_People_SearchVector" ON "People" USING GIN ("SearchVector");

-- =====================================================
-- 6. PERSON NAMES TABLE (Multi-Script Support)
-- =====================================================
CREATE TABLE "PersonNames" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "PersonId" UUID NOT NULL,
    "Script" VARCHAR(10) NOT NULL DEFAULT 'Latin', -- Latin, Arabic, Nobiin
    "Given" VARCHAR(100),
    "Middle" VARCHAR(100),
    "Family" VARCHAR(100),
    "Full" VARCHAR(300),
    "Transliteration" VARCHAR(300),
    "Type" INTEGER NOT NULL DEFAULT 0, -- 0=Primary, 1=Alias, 2=Maiden, 3=Nickname, 4=Tribal, 5=Clan
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_PersonNames_People" FOREIGN KEY ("PersonId") 
        REFERENCES "People" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_PersonNames_PersonId" ON "PersonNames" ("PersonId");
CREATE INDEX "IX_PersonNames_Full" ON "PersonNames" USING GIN ("Full" gin_trgm_ops);
CREATE INDEX "IX_PersonNames_Given" ON "PersonNames" USING GIN ("Given" gin_trgm_ops);
CREATE INDEX "IX_PersonNames_Family" ON "PersonNames" USING GIN ("Family" gin_trgm_ops);

-- =====================================================
-- 7. UNIONS TABLE (Marriages/Partnerships)
-- =====================================================
CREATE TABLE "Unions" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "OrgId" UUID NOT NULL,
    "Type" INTEGER NOT NULL DEFAULT 0, -- 0=Marriage, 1=CivilUnion, 2=Partnership, 3=CommonLaw
    
    -- Start Information
    "StartDate" TIMESTAMP,
    "StartPrecision" INTEGER NOT NULL DEFAULT 5,
    "StartPlaceId" UUID,
    
    -- End Information (Divorce/Separation)
    "EndDate" TIMESTAMP,
    "EndPrecision" INTEGER NOT NULL DEFAULT 5,
    "EndPlaceId" UUID,
    
    "Notes" TEXT,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_Unions_StartPlace" FOREIGN KEY ("StartPlaceId") 
        REFERENCES "Places" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Unions_EndPlace" FOREIGN KEY ("EndPlaceId") 
        REFERENCES "Places" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_Unions_OrgId" ON "Unions" ("OrgId");

-- =====================================================
-- 8. UNION MEMBERS TABLE (Supports Polygamy)
-- =====================================================
CREATE TABLE "UnionMembers" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "UnionId" UUID NOT NULL,
    "PersonId" UUID NOT NULL,
    "Role" VARCHAR(50) NOT NULL DEFAULT 'Spouse',
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_UnionMembers_Unions" FOREIGN KEY ("UnionId") 
        REFERENCES "Unions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UnionMembers_People" FOREIGN KEY ("PersonId") 
        REFERENCES "People" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_UnionMembers_UnionId_PersonId" ON "UnionMembers" ("UnionId", "PersonId");

-- =====================================================
-- 9. PARENT-CHILD RELATIONSHIPS TABLE
-- =====================================================
CREATE TABLE "ParentChildren" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "ParentId" UUID NOT NULL,
    "ChildId" UUID NOT NULL,
    "RelationshipType" INTEGER NOT NULL DEFAULT 0, -- 0=Biological, 1=Adoptive, 2=Step, 3=Foster, 4=Guardian
    "Certainty" VARCHAR(50),
    "Notes" TEXT,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_ParentChildren_Parent" FOREIGN KEY ("ParentId") 
        REFERENCES "People" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ParentChildren_Child" FOREIGN KEY ("ChildId") 
        REFERENCES "People" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_ParentChildren_ParentId" ON "ParentChildren" ("ParentId");
CREATE INDEX "IX_ParentChildren_ChildId" ON "ParentChildren" ("ChildId");
CREATE UNIQUE INDEX "IX_ParentChildren_ParentId_ChildId_Type" 
    ON "ParentChildren" ("ParentId", "ChildId", "RelationshipType");

-- =====================================================
-- 10. MEDIA FILES TABLE
-- =====================================================
CREATE TABLE "MediaFiles" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "OrgId" UUID NOT NULL,
    "Url" VARCHAR(500) NOT NULL,
    "StorageKey" VARCHAR(500) NOT NULL,
    "Kind" INTEGER NOT NULL DEFAULT 0, -- 0=Image, 1=Video, 2=Audio, 3=Document
    "Title" VARCHAR(200),
    "Description" TEXT,
    "CaptureDate" TIMESTAMP,
    "CapturePlaceId" UUID,
    "Visibility" INTEGER NOT NULL DEFAULT 1, -- 0=Public, 1=FamilyOnly, 2=Private
    "Copyright" TEXT,
    "MetadataJson" JSONB,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_MediaFiles_Orgs" FOREIGN KEY ("OrgId") 
        REFERENCES "Orgs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MediaFiles_CapturePlace" FOREIGN KEY ("CapturePlaceId") 
        REFERENCES "Places" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_MediaFiles_OrgId" ON "MediaFiles" ("OrgId");
CREATE INDEX "IX_MediaFiles_StorageKey" ON "MediaFiles" ("StorageKey");

-- =====================================================
-- 11. SOURCES TABLE
-- =====================================================
CREATE TABLE "Sources" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "OrgId" UUID NOT NULL,
    "Title" VARCHAR(300) NOT NULL,
    "Repository" VARCHAR(200),
    "Citation" TEXT,
    "Url" VARCHAR(500),
    "MetadataJson" JSONB,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX "IX_Sources_OrgId" ON "Sources" ("OrgId");
CREATE INDEX "IX_Sources_Title" ON "Sources" ("Title");

-- =====================================================
-- 12. TAGS TABLE
-- =====================================================
CREATE TABLE "Tags" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "OrgId" UUID NOT NULL,
    "Name" VARCHAR(100) NOT NULL,
    "Color" VARCHAR(50),
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE UNIQUE INDEX "IX_Tags_OrgId_Name" ON "Tags" ("OrgId", "Name");

-- =====================================================
-- 13. PERSON-TAG JUNCTION TABLE
-- =====================================================
CREATE TABLE "PersonTags" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "PersonId" UUID NOT NULL,
    "TagId" UUID NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_PersonTags_People" FOREIGN KEY ("PersonId") 
        REFERENCES "People" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PersonTags_Tags" FOREIGN KEY ("TagId") 
        REFERENCES "Tags" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_PersonTags_PersonId_TagId" ON "PersonTags" ("PersonId", "TagId");

-- =====================================================
-- 14. AUDIT LOG TABLE
-- =====================================================
-- UPDATED: ActorId changed from UUID to BIGINT to match AspNetUsers
CREATE TABLE "AuditLogs" (
    "Id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "ActorId" BIGINT NOT NULL,
    "EntityType" VARCHAR(100) NOT NULL,
    "EntityId" UUID NOT NULL,
    "Action" VARCHAR(50) NOT NULL,
    "ChangeJson" JSONB,
    "Timestamp" TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    
    CONSTRAINT "FK_AuditLogs_AspNetUsers" FOREIGN KEY ("ActorId") 
        REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_AuditLogs_ActorId" ON "AuditLogs" ("ActorId");
CREATE INDEX "IX_AuditLogs_EntityType_EntityId" ON "AuditLogs" ("EntityType", "EntityId");
CREATE INDEX "IX_AuditLogs_Timestamp" ON "AuditLogs" ("Timestamp");

-- =====================================================
-- SEED DATA
-- =====================================================

-- Create default organization
INSERT INTO "Orgs" ("Id", "Name", "SettingsJson", "CreatedAt", "UpdatedAt")
VALUES (
    uuid_generate_v4(),
    'Smith Family Tree',
    '{"defaultLanguage":"en","supportedLanguages":["en","ar","nob"]}'::jsonb,
    NOW() AT TIME ZONE 'UTC',
    NOW() AT TIME ZONE 'UTC'
);

-- =====================================================
-- COMMENTS & NOTES
-- =====================================================

COMMENT ON TABLE "AspNetUsers" IS 'ASP.NET Identity users with BIGINT primary keys (int8)';
COMMENT ON TABLE "OrgUsers" IS 'Multi-tenant org membership - UserId references AspNetUsers (BIGINT)';
COMMENT ON TABLE "AuditLogs" IS 'Audit trail - ActorId references AspNetUsers (BIGINT)';
COMMENT ON TABLE "People" IS 'Core genealogy entity with multi-tenant support';
COMMENT ON COLUMN "People"."SearchVector" IS 'Auto-generated tsvector for full-text search';
COMMENT ON TABLE "PersonNames" IS 'Supports multi-script names (Latin, Arabic, Nobiin)';
COMMENT ON TABLE "UnionMembers" IS 'Junction table supporting polygamy (multiple spouses per union)';
COMMENT ON TABLE "ParentChildren" IS 'Parent-child relationships with cycle detection logic in application';

-- =====================================================
-- NOTES FOR VISUAL STUDIO 2022 USAGE
-- =====================================================
/*
1. This schema uses ASP.NET Identity tables (AspNetUsers, AspNetRoles, etc.)
2. The application will create these tables automatically via EF Core
3. OrgUsers.UserId and AuditLogs.ActorId now use BIGINT to match AspNetUsers.Id
4. The old Users table has been removed - all user management is through Identity

To use this schema:
1. Create a new PostgreSQL database
2. Run this script to create the tables
3. Configure your connection string in appsettings.json
4. Run the .NET application - it will seed the admin user automatically

Admin Credentials (created by seed data in Program.cs):
- Email: admin@familytree.demo
- Password: Demo123!

Key Changes from Custom Auth:
- User IDs: UUID → BIGINT (int8)
- OrgUsers.UserId: UUID → BIGINT
- AuditLogs.ActorId: UUID → BIGINT
- Password management: Manual BCrypt → Identity built-in
- User creation: Direct DbContext → UserManager.CreateAsync()
*/

-- =====================================================
-- SUMMARY
-- =====================================================
-- Total Tables: 21 (7 Identity + 14 Application)
-- Multi-Tenant: Yes (OrgId on all entities)
-- Full-Text Search: tsvector with pg_trgm
-- Indexes: 40+ (GIN, B-Tree, Unique)
-- Seed Data: 1 Org (Admin user created by application)
-- =====================================================
