--
-- PostgreSQL database dump
--

\restrict 1e5MjQdcadj0RL6f1OwrZptjEBclcpEA4dYnvnCcJjYTRzD7VOePhKFb8Sc1qh3

-- Dumped from database version 15.3 (Ubuntu 15.3-1.pgdg22.04+1)
-- Dumped by pg_dump version 18.0

-- Started on 2025-12-21 14:25:29

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 250 (class 1259 OID 72644)
-- Name: AdminTreeAssignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AdminTreeAssignments" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "UserId" bigint NOT NULL,
    "TreeId" uuid NOT NULL,
    "AssignedByUserId" bigint,
    "AssignedAt" timestamp with time zone DEFAULT now()
);


ALTER TABLE public."AdminTreeAssignments" OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 72389)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" bigint NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 72394)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 72376)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" bigint NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    "CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "Description" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 72381)
-- Name: AspNetRoles_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoles_Id_seq"
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 72414)
-- Name: AspNetTemp; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetTemp" (
    "Id" integer NOT NULL,
    "ParCode" text NOT NULL,
    "InsertTime" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "AspUser" bigint
);


ALTER TABLE public."AspNetTemp" OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 72420)
-- Name: AspNetTemp_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetTemp" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetTemp_Id_seq"
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 72429)
-- Name: AspNetUserBearerToken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserBearerToken" (
    "IssuedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsRevoked" boolean DEFAULT false NOT NULL,
    "RevokedAt" time with time zone,
    "Value" text NOT NULL,
    "UserId" bigint NOT NULL,
    "RefreshTokenId" bigint NOT NULL,
    "Id" bigint NOT NULL
);


ALTER TABLE public."AspNetUserBearerToken" OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 72436)
-- Name: AspNetUserBearerToken_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserBearerToken" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserBearerToken_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 72395)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" bigint NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 72400)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 72401)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" bigint NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 72406)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" bigint NOT NULL,
    "RoleId" bigint NOT NULL,
    "AssignedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "AssignedBy" integer
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 72409)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" bigint NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    "CreatedAt" timestamp with time zone DEFAULT now()
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 72382)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" bigint NOT NULL,
    "InsertTime" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "IvrProviderId" text,
    "HomePhonenumber" text,
    "UserName" text,
    "NormalizedUserName" text,
    "Email" text,
    "NormalizedEmail" text,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "TwoFactorCode" text,
    "CreatedAt" timestamp with time zone DEFAULT now(),
    "LastLoginAt" timestamp with time zone,
    "FirstName" character varying(100),
    "LastName" character varying(100),
    "PreferredLanguage" character varying(10) DEFAULT 'en'::character varying NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- TOC entry 3796 (class 0 OID 0)
-- Dependencies: 232
-- Name: COLUMN "AspNetUsers"."PreferredLanguage"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."AspNetUsers"."PreferredLanguage" IS 'User preferred language code: en, ar, nob';


--
-- TOC entry 233 (class 1259 OID 72388)
-- Name: AspNetUsers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUsers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUsers_Id_seq"
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 71268)
-- Name: AuditLogs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AuditLogs" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "ActorId" uuid NOT NULL,
    "EntityType" character varying(100) NOT NULL,
    "EntityId" uuid NOT NULL,
    "Action" character varying(50) NOT NULL,
    "ChangeJson" jsonb,
    "Timestamp" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL,
    "IpAddress" character varying(50)
);


ALTER TABLE public."AuditLogs" OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 72928)
-- Name: FamilyRelationshipTypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."FamilyRelationshipTypes" (
    "Id" integer NOT NULL,
    "NameArabic" character varying(100) NOT NULL,
    "NameEnglish" character varying(100) NOT NULL,
    "NameNubian" character varying(100) NOT NULL,
    "Category" character varying(50),
    "SortOrder" integer DEFAULT 0 NOT NULL,
    "IsActive" boolean DEFAULT true NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public."FamilyRelationshipTypes" OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 72927)
-- Name: FamilyRelationshipTypes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."FamilyRelationshipTypes_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."FamilyRelationshipTypes_Id_seq" OWNER TO postgres;

--
-- TOC entry 3797 (class 0 OID 0)
-- Dependencies: 255
-- Name: FamilyRelationshipTypes_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."FamilyRelationshipTypes_Id_seq" OWNED BY public."FamilyRelationshipTypes"."Id";


--
-- TOC entry 225 (class 1259 OID 71206)
-- Name: MediaFiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MediaFiles" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "OrgId" uuid NOT NULL,
    "Url" character varying(500) NOT NULL,
    "StorageKey" character varying(500) NOT NULL,
    "Kind" integer DEFAULT 0 NOT NULL,
    "Title" character varying(200),
    "Description" text,
    "CaptureDate" timestamp without time zone,
    "CapturePlaceId" uuid,
    "Visibility" integer DEFAULT 1 NOT NULL,
    "Copyright" text,
    "MetadataJson" jsonb,
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL,
    "UpdatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL,
    "UploadedByUserId" bigint,
    "Category" character varying(50),
    "FileName" character varying(255) DEFAULT ''::character varying NOT NULL,
    "MimeType" character varying(100),
    "FileSize" bigint DEFAULT 0 NOT NULL,
    "PersonId" uuid,
    "ThumbnailPath" character varying(500),
    "StorageType" integer DEFAULT 1 NOT NULL
);


ALTER TABLE public."MediaFiles" OWNER TO postgres;

--
-- TOC entry 259 (class 1259 OID 72968)
-- Name: NameMappings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."NameMappings" (
    "Id" integer NOT NULL,
    "Arabic" character varying(200),
    "ArabicNormalized" character varying(200),
    "English" character varying(200),
    "EnglishNormalized" character varying(200),
    "Nobiin" character varying(200),
    "NobiinNormalized" character varying(200),
    "Ipa" character varying(200),
    "IsVerified" boolean DEFAULT false NOT NULL,
    "NeedsReview" boolean DEFAULT false NOT NULL,
    "Source" character varying(50),
    "Confidence" double precision,
    "CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "ConfirmedByUserId" bigint,
    "OrgId" uuid
);


ALTER TABLE public."NameMappings" OWNER TO postgres;

--
-- TOC entry 3798 (class 0 OID 0)
-- Dependencies: 259
-- Name: TABLE "NameMappings"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."NameMappings" IS 'Stores verified name transliterations between Arabic, English, and Nobiin scripts for consistency across family trees';


--
-- TOC entry 3799 (class 0 OID 0)
-- Dependencies: 259
-- Name: COLUMN "NameMappings"."NeedsReview"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."NameMappings"."NeedsReview" IS 'Whether this mapping needs human review (low confidence or conflict)';


--
-- TOC entry 3800 (class 0 OID 0)
-- Dependencies: 259
-- Name: COLUMN "NameMappings"."Source"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."NameMappings"."Source" IS 'Source of the mapping: user (manually entered), ged (from GED import), ai (AI-generated)';


--
-- TOC entry 3801 (class 0 OID 0)
-- Dependencies: 259
-- Name: COLUMN "NameMappings"."Confidence"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."NameMappings"."Confidence" IS 'AI confidence score (0.0-1.0) if source is ai';


--
-- TOC entry 258 (class 1259 OID 72967)
-- Name: NameMappings_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."NameMappings_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."NameMappings_Id_seq" OWNER TO postgres;

--
-- TOC entry 3802 (class 0 OID 0)
-- Dependencies: 258
-- Name: NameMappings_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."NameMappings_Id_seq" OWNED BY public."NameMappings"."Id";


--
-- TOC entry 218 (class 1259 OID 71044)
-- Name: OrgUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OrgUsers" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "OrgId" uuid NOT NULL,
    "UserId" bigint NOT NULL,
    "Role" integer DEFAULT 0 NOT NULL,
    "JoinedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL
);


ALTER TABLE public."OrgUsers" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 71019)
-- Name: Orgs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Orgs" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "Name" character varying(200) NOT NULL,
    "SettingsJson" jsonb,
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL,
    "UpdatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL,
    "Description" text,
    "IsPublic" boolean DEFAULT false,
    "AllowCrossTreeLinking" boolean DEFAULT true,
    "CoverImageUrl" character varying(500),
    "OwnerId" bigint,
    "TownId" uuid
);


ALTER TABLE public."Orgs" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 71183)
-- Name: ParentChildren; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ParentChildren" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "ParentId" uuid NOT NULL,
    "ChildId" uuid NOT NULL,
    "RelationshipType" integer DEFAULT 0 NOT NULL,
    "Certainty" character varying(50),
    "Notes" text,
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL
);


ALTER TABLE public."ParentChildren" OWNER TO postgres;

--
-- TOC entry 3803 (class 0 OID 0)
-- Dependencies: 224
-- Name: TABLE "ParentChildren"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."ParentChildren" IS 'Parent-child relationships with cycle detection logic in application';


--
-- TOC entry 220 (class 1259 OID 71084)
-- Name: People; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."People" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "OrgId" uuid NOT NULL,
    "PrimaryName" character varying(200),
    "Sex" integer DEFAULT 2 NOT NULL,
    "Gender" character varying(50),
    "BirthDate" timestamp without time zone,
    "BirthPrecision" integer DEFAULT 5 NOT NULL,
    "BirthPlaceId" uuid,
    "DeathDate" timestamp without time zone,
    "DeathPrecision" integer DEFAULT 5 NOT NULL,
    "DeathPlaceId" uuid,
    "PrivacyLevel" integer DEFAULT 1 NOT NULL,
    "Occupation" text,
    "Education" text,
    "Religion" text,
    "Nationality" text,
    "Ethnicity" text,
    "Notes" text,
    "SearchVector" tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, (((((COALESCE("PrimaryName", ''::character varying))::text || ' '::text) || COALESCE("Occupation", ''::text)) || ' '::text) || COALESCE("Notes", ''::text)))) STORED,
    "IsVerified" boolean DEFAULT false NOT NULL,
    "NeedsReview" boolean DEFAULT false NOT NULL,
    "HasConflict" boolean DEFAULT false NOT NULL,
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL,
    "UpdatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL
);


ALTER TABLE public."People" OWNER TO postgres;

--
-- TOC entry 3804 (class 0 OID 0)
-- Dependencies: 220
-- Name: TABLE "People"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."People" IS 'Core genealogy entity with multi-tenant support';


--
-- TOC entry 3805 (class 0 OID 0)
-- Dependencies: 220
-- Name: COLUMN "People"."SearchVector"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."People"."SearchVector" IS 'Auto-generated tsvector for full-text search';


--
-- TOC entry 249 (class 1259 OID 72605)
-- Name: PersonLinks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PersonLinks" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "SourcePersonId" uuid NOT NULL,
    "TargetPersonId" uuid NOT NULL,
    "LinkType" integer DEFAULT 0 NOT NULL,
    "Confidence" integer DEFAULT 100,
    "Notes" text,
    "CreatedByUserId" bigint,
    "ApprovedByUserId" bigint,
    "Status" integer DEFAULT 0 NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT now(),
    "UpdatedAt" timestamp with time zone DEFAULT now(),
    CONSTRAINT "CK_PersonLinks_Different" CHECK (("SourcePersonId" <> "TargetPersonId"))
);


ALTER TABLE public."PersonLinks" OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 72940)
-- Name: PersonMedia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PersonMedia" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "PersonId" uuid NOT NULL,
    "MediaId" uuid NOT NULL,
    "IsPrimary" boolean DEFAULT false NOT NULL,
    "SortOrder" integer DEFAULT 0 NOT NULL,
    "Notes" text,
    "CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "LinkedAt" timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public."PersonMedia" OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 72698)
-- Name: PersonMediaLinks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PersonMediaLinks" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "PersonId" uuid NOT NULL,
    "MediaId" uuid NOT NULL,
    "IsPrimary" boolean DEFAULT false,
    "SortOrder" integer DEFAULT 0,
    "Notes" text,
    "CreatedAt" timestamp with time zone DEFAULT now(),
    "LinkedAt" timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public."PersonMediaLinks" OWNER TO postgres;

--
-- TOC entry 3806 (class 0 OID 0)
-- Dependencies: 252
-- Name: TABLE "PersonMediaLinks"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."PersonMediaLinks" IS 'Junction table linking People to Media (many-to-many)';


--
-- TOC entry 3807 (class 0 OID 0)
-- Dependencies: 252
-- Name: COLUMN "PersonMediaLinks"."Id"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."PersonMediaLinks"."Id" IS 'Primary key (UUID)';


--
-- TOC entry 3808 (class 0 OID 0)
-- Dependencies: 252
-- Name: COLUMN "PersonMediaLinks"."PersonId"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."PersonMediaLinks"."PersonId" IS 'Foreign key to People table';


--
-- TOC entry 3809 (class 0 OID 0)
-- Dependencies: 252
-- Name: COLUMN "PersonMediaLinks"."MediaId"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."PersonMediaLinks"."MediaId" IS 'Foreign key to MediaFiles table';


--
-- TOC entry 3810 (class 0 OID 0)
-- Dependencies: 252
-- Name: COLUMN "PersonMediaLinks"."IsPrimary"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."PersonMediaLinks"."IsPrimary" IS 'True if this is the primary/profile photo for this person';


--
-- TOC entry 3811 (class 0 OID 0)
-- Dependencies: 252
-- Name: COLUMN "PersonMediaLinks"."SortOrder"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."PersonMediaLinks"."SortOrder" IS 'Display order when showing person media';


--
-- TOC entry 3812 (class 0 OID 0)
-- Dependencies: 252
-- Name: COLUMN "PersonMediaLinks"."Notes"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."PersonMediaLinks"."Notes" IS 'Notes about this person in the media (e.g., position in group photo)';


--
-- TOC entry 3813 (class 0 OID 0)
-- Dependencies: 252
-- Name: COLUMN "PersonMediaLinks"."LinkedAt"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."PersonMediaLinks"."LinkedAt" IS 'Timestamp when this person was linked to this media';


--
-- TOC entry 221 (class 1259 OID 71120)
-- Name: PersonNames; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PersonNames" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "PersonId" uuid NOT NULL,
    "Script" character varying(10) DEFAULT 'Latin'::character varying NOT NULL,
    "Given" character varying(100),
    "Middle" character varying(100),
    "Family" character varying(100),
    "Full" character varying(300),
    "Transliteration" character varying(300),
    "Type" integer DEFAULT 0 NOT NULL,
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL
);


ALTER TABLE public."PersonNames" OWNER TO postgres;

--
-- TOC entry 3814 (class 0 OID 0)
-- Dependencies: 221
-- Name: TABLE "PersonNames"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."PersonNames" IS 'Supports multi-script names (Latin, Arabic, Nobiin)';


--
-- TOC entry 228 (class 1259 OID 71250)
-- Name: PersonTags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PersonTags" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "PersonId" uuid NOT NULL,
    "TagId" uuid NOT NULL,
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL
);


ALTER TABLE public."PersonTags" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 71063)
-- Name: Places; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Places" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "OrgId" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Type" character varying(50),
    "ParentId" uuid,
    "Latitude" double precision,
    "Longitude" double precision,
    "AltNamesJson" jsonb,
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL
);


ALTER TABLE public."Places" OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 72421)
-- Name: RefreshToken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."RefreshToken" (
    "IssuedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsRevoked" boolean DEFAULT false NOT NULL,
    "RevokedAt" timestamp with time zone,
    "Value" text NOT NULL,
    "Id" bigint NOT NULL,
    "UserId" bigint NOT NULL
);


ALTER TABLE public."RefreshToken" OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 72428)
-- Name: RefreshToken_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."RefreshToken" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RefreshToken_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 72437)
-- Name: SignerToken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SignerToken" (
    "IssuedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsRevoked" boolean DEFAULT false NOT NULL,
    "RevokedAt" timestamp with time zone,
    "Value" text NOT NULL,
    "IsUsed" boolean DEFAULT false NOT NULL,
    "UsedAt" timestamp with time zone,
    "IssuedTo" text NOT NULL,
    "IssuedForDocumentId" integer NOT NULL,
    "Id" bigint NOT NULL,
    "RecipientEmail" text NOT NULL,
    "IssuedToId" integer DEFAULT 0 NOT NULL,
    "Passcode" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."SignerToken" OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 72447)
-- Name: SignerToken_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SignerToken" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SignerToken_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 71230)
-- Name: Sources; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sources" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "OrgId" uuid NOT NULL,
    "Title" character varying(300) NOT NULL,
    "Repository" character varying(200),
    "Citation" text,
    "Url" character varying(500),
    "MetadataJson" jsonb,
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL,
    "UpdatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL
);


ALTER TABLE public."Sources" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 71242)
-- Name: Tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tags" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "OrgId" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Color" character varying(50),
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL
);


ALTER TABLE public."Tags" OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 72813)
-- Name: Towns; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Towns" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "NameEn" character varying(200),
    "NameAr" character varying(200),
    "NameLocal" character varying(200),
    "Description" text,
    "Country" character varying(100),
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."Towns" OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 72670)
-- Name: TreeInvitations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TreeInvitations" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TreeId" uuid NOT NULL,
    "Email" character varying(256) NOT NULL,
    "Role" integer DEFAULT 0 NOT NULL,
    "Token" character varying(100) NOT NULL,
    "InvitedByUserId" bigint NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "AcceptedAt" timestamp with time zone,
    "AcceptedByUserId" bigint,
    "CreatedAt" timestamp with time zone DEFAULT now()
);


ALTER TABLE public."TreeInvitations" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 71164)
-- Name: UnionMembers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UnionMembers" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "UnionId" uuid NOT NULL,
    "PersonId" uuid NOT NULL,
    "Role" character varying(50) DEFAULT 'Spouse'::character varying NOT NULL,
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL
);


ALTER TABLE public."UnionMembers" OWNER TO postgres;

--
-- TOC entry 3815 (class 0 OID 0)
-- Dependencies: 223
-- Name: TABLE "UnionMembers"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."UnionMembers" IS 'Junction table supporting polygamy (multiple spouses per union)';


--
-- TOC entry 222 (class 1259 OID 71140)
-- Name: Unions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Unions" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "OrgId" uuid NOT NULL,
    "Type" integer DEFAULT 0 NOT NULL,
    "StartDate" timestamp without time zone,
    "StartPrecision" integer DEFAULT 5 NOT NULL,
    "StartPlaceId" uuid,
    "EndDate" timestamp without time zone,
    "EndPrecision" integer DEFAULT 5 NOT NULL,
    "EndPlaceId" uuid,
    "Notes" text,
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL,
    "UpdatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL
);


ALTER TABLE public."Unions" OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 71030)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "Email" character varying(256) NOT NULL,
    "PasswordHash" text NOT NULL,
    "FirstName" character varying(100),
    "LastName" character varying(100),
    "EmailConfirmed" boolean DEFAULT false NOT NULL,
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL,
    "LastLoginAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL,
    "RefreshToken" text,
    "RefreshTokenExpiryTime" timestamp without time zone
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 3438 (class 2604 OID 72931)
-- Name: FamilyRelationshipTypes Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."FamilyRelationshipTypes" ALTER COLUMN "Id" SET DEFAULT nextval('public."FamilyRelationshipTypes_Id_seq"'::regclass);


--
-- TOC entry 3447 (class 2604 OID 72971)
-- Name: NameMappings Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."NameMappings" ALTER COLUMN "Id" SET DEFAULT nextval('public."NameMappings_Id_seq"'::regclass);


--
-- TOC entry 3560 (class 2606 OID 72650)
-- Name: AdminTreeAssignments AdminTreeAssignments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AdminTreeAssignments"
    ADD CONSTRAINT "AdminTreeAssignments_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3510 (class 2606 OID 71276)
-- Name: AuditLogs AuditLogs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AuditLogs"
    ADD CONSTRAINT "AuditLogs_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3584 (class 2606 OID 72936)
-- Name: FamilyRelationshipTypes FamilyRelationshipTypes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."FamilyRelationshipTypes"
    ADD CONSTRAINT "FamilyRelationshipTypes_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3498 (class 2606 OID 71217)
-- Name: MediaFiles MediaFiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MediaFiles"
    ADD CONSTRAINT "MediaFiles_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3601 (class 2606 OID 72978)
-- Name: NameMappings NameMappings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."NameMappings"
    ADD CONSTRAINT "NameMappings_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3465 (class 2606 OID 71051)
-- Name: OrgUsers OrgUsers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrgUsers"
    ADD CONSTRAINT "OrgUsers_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3457 (class 2606 OID 71028)
-- Name: Orgs Orgs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Orgs"
    ADD CONSTRAINT "Orgs_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3527 (class 2606 OID 72453)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3515 (class 2606 OID 72449)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 3540 (class 2606 OID 72463)
-- Name: AspNetTemp PK_AspNetTemp; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetTemp"
    ADD CONSTRAINT "PK_AspNetTemp" PRIMARY KEY ("Id");


--
-- TOC entry 3530 (class 2606 OID 72455)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3533 (class 2606 OID 72457)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 3536 (class 2606 OID 72459)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 3538 (class 2606 OID 72461)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 3520 (class 2606 OID 72451)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 3544 (class 2606 OID 72467)
-- Name: RefreshToken PK_RefreshToken; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."RefreshToken"
    ADD CONSTRAINT "PK_RefreshToken" PRIMARY KEY ("Id");


--
-- TOC entry 3550 (class 2606 OID 72471)
-- Name: SignerToken PK_SignerToken; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SignerToken"
    ADD CONSTRAINT "PK_SignerToken" PRIMARY KEY ("Id");


--
-- TOC entry 3582 (class 2606 OID 72819)
-- Name: Towns PK_Towns; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Towns"
    ADD CONSTRAINT "PK_Towns" PRIMARY KEY ("Id");


--
-- TOC entry 3491 (class 2606 OID 71192)
-- Name: ParentChildren ParentChildren_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ParentChildren"
    ADD CONSTRAINT "ParentChildren_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3474 (class 2606 OID 71101)
-- Name: People People_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."People"
    ADD CONSTRAINT "People_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3556 (class 2606 OID 72618)
-- Name: PersonLinks PersonLinks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonLinks"
    ADD CONSTRAINT "PersonLinks_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3576 (class 2606 OID 72708)
-- Name: PersonMediaLinks PersonMedia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonMediaLinks"
    ADD CONSTRAINT "PersonMedia_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3592 (class 2606 OID 72951)
-- Name: PersonMedia PersonMedia_pkey1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonMedia"
    ADD CONSTRAINT "PersonMedia_pkey1" PRIMARY KEY ("Id");


--
-- TOC entry 3480 (class 2606 OID 71130)
-- Name: PersonNames PersonNames_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonNames"
    ADD CONSTRAINT "PersonNames_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3508 (class 2606 OID 71256)
-- Name: PersonTags PersonTags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonTags"
    ADD CONSTRAINT "PersonTags_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3548 (class 2606 OID 72469)
-- Name: AspNetUserBearerToken Pk_AspNetUserBearerToken; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserBearerToken"
    ADD CONSTRAINT "Pk_AspNetUserBearerToken" PRIMARY KEY ("Id");


--
-- TOC entry 3469 (class 2606 OID 71071)
-- Name: Places Places_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Places"
    ADD CONSTRAINT "Places_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3502 (class 2606 OID 71239)
-- Name: Sources Sources_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sources"
    ADD CONSTRAINT "Sources_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3505 (class 2606 OID 71248)
-- Name: Tags Tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tags"
    ADD CONSTRAINT "Tags_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3569 (class 2606 OID 72679)
-- Name: TreeInvitations TreeInvitations_Token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TreeInvitations"
    ADD CONSTRAINT "TreeInvitations_Token_key" UNIQUE ("Token");


--
-- TOC entry 3571 (class 2606 OID 72677)
-- Name: TreeInvitations TreeInvitations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TreeInvitations"
    ADD CONSTRAINT "TreeInvitations_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3564 (class 2606 OID 72652)
-- Name: AdminTreeAssignments UQ_AdminTreeAssignments_User_Tree; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AdminTreeAssignments"
    ADD CONSTRAINT "UQ_AdminTreeAssignments_User_Tree" UNIQUE ("UserId", "TreeId");


--
-- TOC entry 3558 (class 2606 OID 72620)
-- Name: PersonLinks UQ_PersonLinks_Source_Target; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonLinks"
    ADD CONSTRAINT "UQ_PersonLinks_Source_Target" UNIQUE ("SourcePersonId", "TargetPersonId");


--
-- TOC entry 3578 (class 2606 OID 72710)
-- Name: PersonMediaLinks UQ_PersonMedia_Person_Media; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonMediaLinks"
    ADD CONSTRAINT "UQ_PersonMedia_Person_Media" UNIQUE ("PersonId", "MediaId");


--
-- TOC entry 3486 (class 2606 OID 71171)
-- Name: UnionMembers UnionMembers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UnionMembers"
    ADD CONSTRAINT "UnionMembers_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3483 (class 2606 OID 71152)
-- Name: Unions Unions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Unions"
    ADD CONSTRAINT "Unions_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3460 (class 2606 OID 71042)
-- Name: Users Users_Email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_Email_key" UNIQUE ("Email");


--
-- TOC entry 3462 (class 2606 OID 71040)
-- Name: Users Users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3542 (class 2606 OID 72465)
-- Name: AspNetTemp unique_aspuser_constraint; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetTemp"
    ADD CONSTRAINT unique_aspuser_constraint UNIQUE ("AspUser");


--
-- TOC entry 3518 (class 1259 OID 72472)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 3561 (class 1259 OID 72669)
-- Name: IX_AdminTreeAssignments_TreeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AdminTreeAssignments_TreeId" ON public."AdminTreeAssignments" USING btree ("TreeId");


--
-- TOC entry 3562 (class 1259 OID 72668)
-- Name: IX_AdminTreeAssignments_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AdminTreeAssignments_UserId" ON public."AdminTreeAssignments" USING btree ("UserId");


--
-- TOC entry 3525 (class 1259 OID 72478)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 3528 (class 1259 OID 72479)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 3531 (class 1259 OID 72480)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 3534 (class 1259 OID 72481)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 3511 (class 1259 OID 71282)
-- Name: IX_AuditLogs_ActorId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_ActorId" ON public."AuditLogs" USING btree ("ActorId");


--
-- TOC entry 3512 (class 1259 OID 71283)
-- Name: IX_AuditLogs_EntityType_EntityId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_EntityType_EntityId" ON public."AuditLogs" USING btree ("EntityType", "EntityId");


--
-- TOC entry 3513 (class 1259 OID 71284)
-- Name: IX_AuditLogs_Timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_Timestamp" ON public."AuditLogs" USING btree ("Timestamp");


--
-- TOC entry 3585 (class 1259 OID 72938)
-- Name: IX_FamilyRelationshipTypes_Category; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_FamilyRelationshipTypes_Category" ON public."FamilyRelationshipTypes" USING btree ("Category");


--
-- TOC entry 3586 (class 1259 OID 72939)
-- Name: IX_FamilyRelationshipTypes_IsActive; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_FamilyRelationshipTypes_IsActive" ON public."FamilyRelationshipTypes" USING btree ("IsActive");


--
-- TOC entry 3587 (class 1259 OID 72937)
-- Name: IX_FamilyRelationshipTypes_NameEnglish; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_FamilyRelationshipTypes_NameEnglish" ON public."FamilyRelationshipTypes" USING btree ("NameEnglish");


--
-- TOC entry 3492 (class 1259 OID 72729)
-- Name: IX_MediaFiles_Category; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MediaFiles_Category" ON public."MediaFiles" USING btree ("Category");


--
-- TOC entry 3493 (class 1259 OID 71228)
-- Name: IX_MediaFiles_OrgId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MediaFiles_OrgId" ON public."MediaFiles" USING btree ("OrgId");


--
-- TOC entry 3494 (class 1259 OID 72893)
-- Name: IX_MediaFiles_PersonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MediaFiles_PersonId" ON public."MediaFiles" USING btree ("PersonId");


--
-- TOC entry 3495 (class 1259 OID 71229)
-- Name: IX_MediaFiles_StorageKey; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MediaFiles_StorageKey" ON public."MediaFiles" USING btree ("StorageKey");


--
-- TOC entry 3496 (class 1259 OID 72728)
-- Name: IX_MediaFiles_UploadedByUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MediaFiles_UploadedByUserId" ON public."MediaFiles" USING btree ("UploadedByUserId");


--
-- TOC entry 3593 (class 1259 OID 72989)
-- Name: IX_NameMappings_ArabicNormalized; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_NameMappings_ArabicNormalized" ON public."NameMappings" USING btree ("ArabicNormalized");


--
-- TOC entry 3594 (class 1259 OID 72995)
-- Name: IX_NameMappings_ConfirmedByUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_NameMappings_ConfirmedByUserId" ON public."NameMappings" USING btree ("ConfirmedByUserId");


--
-- TOC entry 3595 (class 1259 OID 72990)
-- Name: IX_NameMappings_EnglishNormalized; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_NameMappings_EnglishNormalized" ON public."NameMappings" USING btree ("EnglishNormalized");


--
-- TOC entry 3596 (class 1259 OID 72993)
-- Name: IX_NameMappings_IsVerified; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_NameMappings_IsVerified" ON public."NameMappings" USING btree ("IsVerified");


--
-- TOC entry 3597 (class 1259 OID 72992)
-- Name: IX_NameMappings_NeedsReview; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_NameMappings_NeedsReview" ON public."NameMappings" USING btree ("NeedsReview");


--
-- TOC entry 3598 (class 1259 OID 72991)
-- Name: IX_NameMappings_NobiinNormalized; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_NameMappings_NobiinNormalized" ON public."NameMappings" USING btree ("NobiinNormalized");


--
-- TOC entry 3599 (class 1259 OID 72994)
-- Name: IX_NameMappings_OrgId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_NameMappings_OrgId" ON public."NameMappings" USING btree ("OrgId");


--
-- TOC entry 3463 (class 1259 OID 72544)
-- Name: IX_OrgUsers_OrgId_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_OrgUsers_OrgId_UserId" ON public."OrgUsers" USING btree ("OrgId", "UserId");


--
-- TOC entry 3452 (class 1259 OID 72604)
-- Name: IX_Orgs_IsPublic; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Orgs_IsPublic" ON public."Orgs" USING btree ("IsPublic");


--
-- TOC entry 3453 (class 1259 OID 71029)
-- Name: IX_Orgs_Name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Orgs_Name" ON public."Orgs" USING btree ("Name");


--
-- TOC entry 3454 (class 1259 OID 72603)
-- Name: IX_Orgs_OwnerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Orgs_OwnerId" ON public."Orgs" USING btree ("OwnerId");


--
-- TOC entry 3455 (class 1259 OID 72822)
-- Name: IX_Orgs_TownId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Orgs_TownId" ON public."Orgs" USING btree ("TownId");


--
-- TOC entry 3487 (class 1259 OID 71204)
-- Name: IX_ParentChildren_ChildId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ParentChildren_ChildId" ON public."ParentChildren" USING btree ("ChildId");


--
-- TOC entry 3488 (class 1259 OID 71203)
-- Name: IX_ParentChildren_ParentId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ParentChildren_ParentId" ON public."ParentChildren" USING btree ("ParentId");


--
-- TOC entry 3489 (class 1259 OID 71205)
-- Name: IX_ParentChildren_ParentId_ChildId_Type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_ParentChildren_ParentId_ChildId_Type" ON public."ParentChildren" USING btree ("ParentId", "ChildId", "RelationshipType");


--
-- TOC entry 3470 (class 1259 OID 71117)
-- Name: IX_People_OrgId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_People_OrgId" ON public."People" USING btree ("OrgId");


--
-- TOC entry 3471 (class 1259 OID 71118)
-- Name: IX_People_PrimaryName; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_People_PrimaryName" ON public."People" USING btree ("PrimaryName");


--
-- TOC entry 3472 (class 1259 OID 71119)
-- Name: IX_People_SearchVector; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_People_SearchVector" ON public."People" USING gin ("SearchVector");


--
-- TOC entry 3552 (class 1259 OID 72641)
-- Name: IX_PersonLinks_SourcePersonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PersonLinks_SourcePersonId" ON public."PersonLinks" USING btree ("SourcePersonId");


--
-- TOC entry 3553 (class 1259 OID 72643)
-- Name: IX_PersonLinks_Status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PersonLinks_Status" ON public."PersonLinks" USING btree ("Status");


--
-- TOC entry 3554 (class 1259 OID 72642)
-- Name: IX_PersonLinks_TargetPersonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PersonLinks_TargetPersonId" ON public."PersonLinks" USING btree ("TargetPersonId");


--
-- TOC entry 3572 (class 1259 OID 72722)
-- Name: IX_PersonMediaLinks_MediaId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PersonMediaLinks_MediaId" ON public."PersonMediaLinks" USING btree ("MediaId");


--
-- TOC entry 3573 (class 1259 OID 72721)
-- Name: IX_PersonMediaLinks_PersonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PersonMediaLinks_PersonId" ON public."PersonMediaLinks" USING btree ("PersonId");


--
-- TOC entry 3574 (class 1259 OID 72894)
-- Name: IX_PersonMediaLinks_PersonId_MediaId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_PersonMediaLinks_PersonId_MediaId" ON public."PersonMediaLinks" USING btree ("PersonId", "MediaId");


--
-- TOC entry 3588 (class 1259 OID 72963)
-- Name: IX_PersonMedia_MediaId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PersonMedia_MediaId" ON public."PersonMedia" USING btree ("MediaId");


--
-- TOC entry 3589 (class 1259 OID 72962)
-- Name: IX_PersonMedia_PersonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PersonMedia_PersonId" ON public."PersonMedia" USING btree ("PersonId");


--
-- TOC entry 3590 (class 1259 OID 72964)
-- Name: IX_PersonMedia_PersonId_MediaId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_PersonMedia_PersonId_MediaId" ON public."PersonMedia" USING btree ("PersonId", "MediaId");


--
-- TOC entry 3475 (class 1259 OID 71139)
-- Name: IX_PersonNames_Family; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PersonNames_Family" ON public."PersonNames" USING gin ("Family" public.gin_trgm_ops);


--
-- TOC entry 3476 (class 1259 OID 71137)
-- Name: IX_PersonNames_Full; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PersonNames_Full" ON public."PersonNames" USING gin ("Full" public.gin_trgm_ops);


--
-- TOC entry 3477 (class 1259 OID 71138)
-- Name: IX_PersonNames_Given; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PersonNames_Given" ON public."PersonNames" USING gin ("Given" public.gin_trgm_ops);


--
-- TOC entry 3478 (class 1259 OID 71136)
-- Name: IX_PersonNames_PersonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PersonNames_PersonId" ON public."PersonNames" USING btree ("PersonId");


--
-- TOC entry 3506 (class 1259 OID 71267)
-- Name: IX_PersonTags_PersonId_TagId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_PersonTags_PersonId_TagId" ON public."PersonTags" USING btree ("PersonId", "TagId");


--
-- TOC entry 3466 (class 1259 OID 71082)
-- Name: IX_Places_OrgId_Name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Places_OrgId_Name" ON public."Places" USING btree ("OrgId", "Name");


--
-- TOC entry 3467 (class 1259 OID 71083)
-- Name: IX_Places_ParentId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Places_ParentId" ON public."Places" USING btree ("ParentId");


--
-- TOC entry 3499 (class 1259 OID 71240)
-- Name: IX_Sources_OrgId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sources_OrgId" ON public."Sources" USING btree ("OrgId");


--
-- TOC entry 3500 (class 1259 OID 71241)
-- Name: IX_Sources_Title; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sources_Title" ON public."Sources" USING btree ("Title");


--
-- TOC entry 3503 (class 1259 OID 71249)
-- Name: IX_Tags_OrgId_Name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Tags_OrgId_Name" ON public."Tags" USING btree ("OrgId", "Name");


--
-- TOC entry 3579 (class 1259 OID 72821)
-- Name: IX_Towns_Country; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Towns_Country" ON public."Towns" USING btree ("Country");


--
-- TOC entry 3580 (class 1259 OID 72820)
-- Name: IX_Towns_Name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Towns_Name" ON public."Towns" USING btree ("Name");


--
-- TOC entry 3565 (class 1259 OID 72696)
-- Name: IX_TreeInvitations_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TreeInvitations_Email" ON public."TreeInvitations" USING btree ("Email");


--
-- TOC entry 3566 (class 1259 OID 72697)
-- Name: IX_TreeInvitations_Token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TreeInvitations_Token" ON public."TreeInvitations" USING btree ("Token");


--
-- TOC entry 3567 (class 1259 OID 72695)
-- Name: IX_TreeInvitations_TreeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TreeInvitations_TreeId" ON public."TreeInvitations" USING btree ("TreeId");


--
-- TOC entry 3484 (class 1259 OID 71182)
-- Name: IX_UnionMembers_UnionId_PersonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_UnionMembers_UnionId_PersonId" ON public."UnionMembers" USING btree ("UnionId", "PersonId");


--
-- TOC entry 3481 (class 1259 OID 71163)
-- Name: IX_Unions_OrgId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Unions_OrgId" ON public."Unions" USING btree ("OrgId");


--
-- TOC entry 3458 (class 1259 OID 71043)
-- Name: IX_Users_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Email" ON public."Users" USING btree ("Email");


--
-- TOC entry 3516 (class 1259 OID 72476)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 3521 (class 1259 OID 72473)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 3545 (class 1259 OID 72482)
-- Name: idx_refreshtoken_value; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_refreshtoken_value ON public."RefreshToken" USING btree ("Value");


--
-- TOC entry 3517 (class 1259 OID 72477)
-- Name: idx_role_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_role_name ON public."AspNetRoles" USING btree ("Name");


--
-- TOC entry 3551 (class 1259 OID 72484)
-- Name: idx_signertoken_value; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_signertoken_value ON public."SignerToken" USING btree ("Value");


--
-- TOC entry 3522 (class 1259 OID 72474)
-- Name: idx_user_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_user_email ON public."AspNetUsers" USING btree ("Email");


--
-- TOC entry 3523 (class 1259 OID 72475)
-- Name: idx_user_username; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_user_username ON public."AspNetUsers" USING btree ("UserName");


--
-- TOC entry 3524 (class 1259 OID 72966)
-- Name: idx_users_preferred_language; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_users_preferred_language ON public."AspNetUsers" USING btree ("PreferredLanguage");


--
-- TOC entry 3546 (class 1259 OID 72483)
-- Name: refreshtoken_userid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX refreshtoken_userid_idx ON public."RefreshToken" USING btree ("UserId");


--
-- TOC entry 3637 (class 2606 OID 72663)
-- Name: AdminTreeAssignments AdminTreeAssignments_AssignedByUserId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AdminTreeAssignments"
    ADD CONSTRAINT "AdminTreeAssignments_AssignedByUserId_fkey" FOREIGN KEY ("AssignedByUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE SET NULL;


--
-- TOC entry 3638 (class 2606 OID 72658)
-- Name: AdminTreeAssignments AdminTreeAssignments_TreeId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AdminTreeAssignments"
    ADD CONSTRAINT "AdminTreeAssignments_TreeId_fkey" FOREIGN KEY ("TreeId") REFERENCES public."Orgs"("Id") ON DELETE CASCADE;


--
-- TOC entry 3639 (class 2606 OID 72653)
-- Name: AdminTreeAssignments AdminTreeAssignments_UserId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AdminTreeAssignments"
    ADD CONSTRAINT "AdminTreeAssignments_UserId_fkey" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3631 (class 2606 OID 72515)
-- Name: AspNetUserBearerToken FK_AspNetBearerToken_RefreshToken; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserBearerToken"
    ADD CONSTRAINT "FK_AspNetBearerToken_RefreshToken" FOREIGN KEY ("RefreshTokenId") REFERENCES public."RefreshToken"("Id");


--
-- TOC entry 3625 (class 2606 OID 72485)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3626 (class 2606 OID 72490)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3627 (class 2606 OID 72495)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3628 (class 2606 OID 72500)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3629 (class 2606 OID 72505)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3630 (class 2606 OID 72510)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3624 (class 2606 OID 71277)
-- Name: AuditLogs FK_AuditLogs_Actor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AuditLogs"
    ADD CONSTRAINT "FK_AuditLogs_Actor" FOREIGN KEY ("ActorId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3618 (class 2606 OID 71223)
-- Name: MediaFiles FK_MediaFiles_CapturePlace; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MediaFiles"
    ADD CONSTRAINT "FK_MediaFiles_CapturePlace" FOREIGN KEY ("CapturePlaceId") REFERENCES public."Places"("Id") ON DELETE SET NULL;


--
-- TOC entry 3619 (class 2606 OID 71218)
-- Name: MediaFiles FK_MediaFiles_Orgs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MediaFiles"
    ADD CONSTRAINT "FK_MediaFiles_Orgs" FOREIGN KEY ("OrgId") REFERENCES public."Orgs"("Id") ON DELETE CASCADE;


--
-- TOC entry 3620 (class 2606 OID 72888)
-- Name: MediaFiles FK_MediaFiles_Person; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MediaFiles"
    ADD CONSTRAINT "FK_MediaFiles_Person" FOREIGN KEY ("PersonId") REFERENCES public."People"("Id") ON DELETE SET NULL;


--
-- TOC entry 3604 (class 2606 OID 72550)
-- Name: OrgUsers FK_OrgUsers_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrgUsers"
    ADD CONSTRAINT "FK_OrgUsers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3605 (class 2606 OID 71052)
-- Name: OrgUsers FK_OrgUsers_Orgs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrgUsers"
    ADD CONSTRAINT "FK_OrgUsers_Orgs" FOREIGN KEY ("OrgId") REFERENCES public."Orgs"("Id") ON DELETE CASCADE;


--
-- TOC entry 3602 (class 2606 OID 72823)
-- Name: Orgs FK_Orgs_Towns_TownId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Orgs"
    ADD CONSTRAINT "FK_Orgs_Towns_TownId" FOREIGN KEY ("TownId") REFERENCES public."Towns"("Id") ON DELETE SET NULL;


--
-- TOC entry 3616 (class 2606 OID 71198)
-- Name: ParentChildren FK_ParentChildren_Child; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ParentChildren"
    ADD CONSTRAINT "FK_ParentChildren_Child" FOREIGN KEY ("ChildId") REFERENCES public."People"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3617 (class 2606 OID 71193)
-- Name: ParentChildren FK_ParentChildren_Parent; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ParentChildren"
    ADD CONSTRAINT "FK_ParentChildren_Parent" FOREIGN KEY ("ParentId") REFERENCES public."People"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3608 (class 2606 OID 71107)
-- Name: People FK_People_BirthPlace; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."People"
    ADD CONSTRAINT "FK_People_BirthPlace" FOREIGN KEY ("BirthPlaceId") REFERENCES public."Places"("Id") ON DELETE SET NULL;


--
-- TOC entry 3609 (class 2606 OID 71112)
-- Name: People FK_People_DeathPlace; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."People"
    ADD CONSTRAINT "FK_People_DeathPlace" FOREIGN KEY ("DeathPlaceId") REFERENCES public."Places"("Id") ON DELETE SET NULL;


--
-- TOC entry 3610 (class 2606 OID 71102)
-- Name: People FK_People_Orgs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."People"
    ADD CONSTRAINT "FK_People_Orgs" FOREIGN KEY ("OrgId") REFERENCES public."Orgs"("Id") ON DELETE CASCADE;


--
-- TOC entry 3645 (class 2606 OID 72957)
-- Name: PersonMedia FK_PersonMedia_MediaFiles_MediaId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonMedia"
    ADD CONSTRAINT "FK_PersonMedia_MediaFiles_MediaId" FOREIGN KEY ("MediaId") REFERENCES public."MediaFiles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3646 (class 2606 OID 72952)
-- Name: PersonMedia FK_PersonMedia_People_PersonId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonMedia"
    ADD CONSTRAINT "FK_PersonMedia_People_PersonId" FOREIGN KEY ("PersonId") REFERENCES public."People"("Id") ON DELETE CASCADE;


--
-- TOC entry 3611 (class 2606 OID 71131)
-- Name: PersonNames FK_PersonNames_People; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonNames"
    ADD CONSTRAINT "FK_PersonNames_People" FOREIGN KEY ("PersonId") REFERENCES public."People"("Id") ON DELETE CASCADE;


--
-- TOC entry 3622 (class 2606 OID 71257)
-- Name: PersonTags FK_PersonTags_People; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonTags"
    ADD CONSTRAINT "FK_PersonTags_People" FOREIGN KEY ("PersonId") REFERENCES public."People"("Id") ON DELETE CASCADE;


--
-- TOC entry 3623 (class 2606 OID 71262)
-- Name: PersonTags FK_PersonTags_Tags; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonTags"
    ADD CONSTRAINT "FK_PersonTags_Tags" FOREIGN KEY ("TagId") REFERENCES public."Tags"("Id") ON DELETE CASCADE;


--
-- TOC entry 3606 (class 2606 OID 71072)
-- Name: Places FK_Places_Orgs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Places"
    ADD CONSTRAINT "FK_Places_Orgs" FOREIGN KEY ("OrgId") REFERENCES public."Orgs"("Id") ON DELETE CASCADE;


--
-- TOC entry 3607 (class 2606 OID 71077)
-- Name: Places FK_Places_ParentPlace; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Places"
    ADD CONSTRAINT "FK_Places_ParentPlace" FOREIGN KEY ("ParentId") REFERENCES public."Places"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3614 (class 2606 OID 71177)
-- Name: UnionMembers FK_UnionMembers_People; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UnionMembers"
    ADD CONSTRAINT "FK_UnionMembers_People" FOREIGN KEY ("PersonId") REFERENCES public."People"("Id") ON DELETE CASCADE;


--
-- TOC entry 3615 (class 2606 OID 71172)
-- Name: UnionMembers FK_UnionMembers_Unions; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UnionMembers"
    ADD CONSTRAINT "FK_UnionMembers_Unions" FOREIGN KEY ("UnionId") REFERENCES public."Unions"("Id") ON DELETE CASCADE;


--
-- TOC entry 3612 (class 2606 OID 71158)
-- Name: Unions FK_Unions_EndPlace; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Unions"
    ADD CONSTRAINT "FK_Unions_EndPlace" FOREIGN KEY ("EndPlaceId") REFERENCES public."Places"("Id") ON DELETE SET NULL;


--
-- TOC entry 3613 (class 2606 OID 71153)
-- Name: Unions FK_Unions_StartPlace; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Unions"
    ADD CONSTRAINT "FK_Unions_StartPlace" FOREIGN KEY ("StartPlaceId") REFERENCES public."Places"("Id") ON DELETE SET NULL;


--
-- TOC entry 3632 (class 2606 OID 72520)
-- Name: AspNetUserBearerToken Fk_AspNetUserBearerToken_AspNetUsers; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserBearerToken"
    ADD CONSTRAINT "Fk_AspNetUserBearerToken_AspNetUsers" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id");


--
-- TOC entry 3621 (class 2606 OID 72723)
-- Name: MediaFiles MediaFiles_UploadedByUserId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MediaFiles"
    ADD CONSTRAINT "MediaFiles_UploadedByUserId_fkey" FOREIGN KEY ("UploadedByUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE SET NULL;


--
-- TOC entry 3647 (class 2606 OID 72979)
-- Name: NameMappings NameMappings_ConfirmedByUserId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."NameMappings"
    ADD CONSTRAINT "NameMappings_ConfirmedByUserId_fkey" FOREIGN KEY ("ConfirmedByUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE SET NULL;


--
-- TOC entry 3648 (class 2606 OID 72984)
-- Name: NameMappings NameMappings_OrgId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."NameMappings"
    ADD CONSTRAINT "NameMappings_OrgId_fkey" FOREIGN KEY ("OrgId") REFERENCES public."Orgs"("Id") ON DELETE SET NULL;


--
-- TOC entry 3603 (class 2606 OID 72598)
-- Name: Orgs Orgs_OwnerId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Orgs"
    ADD CONSTRAINT "Orgs_OwnerId_fkey" FOREIGN KEY ("OwnerId") REFERENCES public."AspNetUsers"("Id") ON DELETE SET NULL;


--
-- TOC entry 3633 (class 2606 OID 72636)
-- Name: PersonLinks PersonLinks_ApprovedByUserId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonLinks"
    ADD CONSTRAINT "PersonLinks_ApprovedByUserId_fkey" FOREIGN KEY ("ApprovedByUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE SET NULL;


--
-- TOC entry 3634 (class 2606 OID 72631)
-- Name: PersonLinks PersonLinks_CreatedByUserId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonLinks"
    ADD CONSTRAINT "PersonLinks_CreatedByUserId_fkey" FOREIGN KEY ("CreatedByUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE SET NULL;


--
-- TOC entry 3635 (class 2606 OID 72621)
-- Name: PersonLinks PersonLinks_SourcePersonId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonLinks"
    ADD CONSTRAINT "PersonLinks_SourcePersonId_fkey" FOREIGN KEY ("SourcePersonId") REFERENCES public."People"("Id") ON DELETE CASCADE;


--
-- TOC entry 3636 (class 2606 OID 72626)
-- Name: PersonLinks PersonLinks_TargetPersonId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonLinks"
    ADD CONSTRAINT "PersonLinks_TargetPersonId_fkey" FOREIGN KEY ("TargetPersonId") REFERENCES public."People"("Id") ON DELETE CASCADE;


--
-- TOC entry 3643 (class 2606 OID 72716)
-- Name: PersonMediaLinks PersonMedia_MediaId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonMediaLinks"
    ADD CONSTRAINT "PersonMedia_MediaId_fkey" FOREIGN KEY ("MediaId") REFERENCES public."MediaFiles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3644 (class 2606 OID 72711)
-- Name: PersonMediaLinks PersonMedia_PersonId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PersonMediaLinks"
    ADD CONSTRAINT "PersonMedia_PersonId_fkey" FOREIGN KEY ("PersonId") REFERENCES public."People"("Id") ON DELETE CASCADE;


--
-- TOC entry 3640 (class 2606 OID 72690)
-- Name: TreeInvitations TreeInvitations_AcceptedByUserId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TreeInvitations"
    ADD CONSTRAINT "TreeInvitations_AcceptedByUserId_fkey" FOREIGN KEY ("AcceptedByUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE SET NULL;


--
-- TOC entry 3641 (class 2606 OID 72685)
-- Name: TreeInvitations TreeInvitations_InvitedByUserId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TreeInvitations"
    ADD CONSTRAINT "TreeInvitations_InvitedByUserId_fkey" FOREIGN KEY ("InvitedByUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3642 (class 2606 OID 72680)
-- Name: TreeInvitations TreeInvitations_TreeId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TreeInvitations"
    ADD CONSTRAINT "TreeInvitations_TreeId_fkey" FOREIGN KEY ("TreeId") REFERENCES public."Orgs"("Id") ON DELETE CASCADE;


-- Completed on 2025-12-21 14:25:34

--
-- PostgreSQL database dump complete
--

\unrestrict 1e5MjQdcadj0RL6f1OwrZptjEBclcpEA4dYnvnCcJjYTRzD7VOePhKFb8Sc1qh3

