--
-- PostgreSQL database dump
--

\restrict dq1kpPNIRUsjoaB9IHy2ufESwqdeCEh4WzRYYPeMPIVhQDMCyu7VgnNw0U7dvJ0

-- Dumped from database version 15.3 (Ubuntu 15.3-1.pgdg22.04+1)
-- Dumped by pg_dump version 18.0

-- Started on 2025-12-20 11:26:35

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false); 
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 243 (class 1259 OID 72421)
-- Name: RefreshToken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."RefreshToken" (
    "IssuedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsRevoked" boolean DEFAULT false NOT NULL,
    "RevokedAt" timestamp with time zone,
    "Value" text NOT NULL,
    "Id" bigint NOT NULL,
    "UserId" bigint NOT NULL
);


ALTER TABLE public."RefreshToken" OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 72428)
-- Name: RefreshToken_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."RefreshToken" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RefreshToken_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 72437)
-- Name: SignerToken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SignerToken" (
    "IssuedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsRevoked" boolean DEFAULT false NOT NULL,
    "RevokedAt" timestamp with time zone,
    "Value" text NOT NULL,
    "IsUsed" boolean DEFAULT false NOT NULL,
    "UsedAt" timestamp with time zone,
    "IssuedTo" text NOT NULL,
    "IssuedForDocumentId" integer NOT NULL,
    "Id" bigint NOT NULL,
    "RecipientEmail" text NOT NULL,
    "IssuedToId" integer DEFAULT 0 NOT NULL,
    "Passcode" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."SignerToken" OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 72447)
-- Name: SignerToken_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SignerToken" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SignerToken_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 71230)
-- Name: Sources; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sources" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "OrgId" uuid NOT NULL,
    "Title" character varying(300) NOT NULL,
    "Repository" character varying(200),
    "Citation" text,
    "Url" character varying(500),
    "MetadataJson" jsonb,
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL,
    "UpdatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL
);


ALTER TABLE public."Sources" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 71242)
-- Name: Tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tags" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "OrgId" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Color" character varying(50),
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL
);


ALTER TABLE public."Tags" OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 72813)
-- Name: Towns; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Towns" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "NameEn" character varying(200),
    "NameAr" character varying(200),
    "NameLocal" character varying(200),
    "Description" text,
    "Country" character varying(100),
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."Towns" OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 72670)
-- Name: TreeInvitations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TreeInvitations" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "TreeId" uuid NOT NULL,
    "Email" character varying(256) NOT NULL,
    "Role" integer DEFAULT 0 NOT NULL,
    "Token" character varying(100) NOT NULL,
    "InvitedByUserId" bigint NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "AcceptedAt" timestamp with time zone,
    "AcceptedByUserId" bigint,
    "CreatedAt" timestamp with time zone DEFAULT now()
);


ALTER TABLE public."TreeInvitations" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 71164)
-- Name: UnionMembers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UnionMembers" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "UnionId" uuid NOT NULL,
    "PersonId" uuid NOT NULL,
    "Role" character varying(50) DEFAULT 'Spouse'::character varying NOT NULL,
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL
);


ALTER TABLE public."UnionMembers" OWNER TO postgres;

--
-- TOC entry 3562 (class 0 OID 0)
-- Dependencies: 223
-- Name: TABLE "UnionMembers"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."UnionMembers" IS 'Junction table supporting polygamy (multiple spouses per union)';


--
-- TOC entry 222 (class 1259 OID 71140)
-- Name: Unions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Unions" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "OrgId" uuid NOT NULL,
    "Type" integer DEFAULT 0 NOT NULL,
    "StartDate" timestamp without time zone,
    "StartPrecision" integer DEFAULT 5 NOT NULL,
    "StartPlaceId" uuid,
    "EndDate" timestamp without time zone,
    "EndPrecision" integer DEFAULT 5 NOT NULL,
    "EndPlaceId" uuid,
    "Notes" text,
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL,
    "UpdatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL
);


ALTER TABLE public."Unions" OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 71030)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    "Email" character varying(256) NOT NULL,
    "PasswordHash" text NOT NULL,
    "FirstName" character varying(100),
    "LastName" character varying(100),
    "EmailConfirmed" boolean DEFAULT false NOT NULL,
    "CreatedAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL,
    "LastLoginAt" timestamp without time zone DEFAULT (now() AT TIME ZONE 'UTC'::text) NOT NULL,
    "RefreshToken" text,
    "RefreshTokenExpiryTime" timestamp without time zone
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 3391 (class 2606 OID 72467)
-- Name: RefreshToken PK_RefreshToken; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."RefreshToken"
    ADD CONSTRAINT "PK_RefreshToken" PRIMARY KEY ("Id");


--
-- TOC entry 3395 (class 2606 OID 72471)
-- Name: SignerToken PK_SignerToken; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SignerToken"
    ADD CONSTRAINT "PK_SignerToken" PRIMARY KEY ("Id");


--
-- TOC entry 3407 (class 2606 OID 72819)
-- Name: Towns PK_Towns; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Towns"
    ADD CONSTRAINT "PK_Towns" PRIMARY KEY ("Id");


--
-- TOC entry 3386 (class 2606 OID 71239)
-- Name: Sources Sources_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sources"
    ADD CONSTRAINT "Sources_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3389 (class 2606 OID 71248)
-- Name: Tags Tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tags"
    ADD CONSTRAINT "Tags_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3401 (class 2606 OID 72679)
-- Name: TreeInvitations TreeInvitations_Token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TreeInvitations"
    ADD CONSTRAINT "TreeInvitations_Token_key" UNIQUE ("Token");


--
-- TOC entry 3403 (class 2606 OID 72677)
-- Name: TreeInvitations TreeInvitations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TreeInvitations"
    ADD CONSTRAINT "TreeInvitations_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3382 (class 2606 OID 71171)
-- Name: UnionMembers UnionMembers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UnionMembers"
    ADD CONSTRAINT "UnionMembers_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3379 (class 2606 OID 71152)
-- Name: Unions Unions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Unions"
    ADD CONSTRAINT "Unions_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3374 (class 2606 OID 71042)
-- Name: Users Users_Email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_Email_key" UNIQUE ("Email");


--
-- TOC entry 3376 (class 2606 OID 71040)
-- Name: Users Users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3383 (class 1259 OID 71240)
-- Name: IX_Sources_OrgId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sources_OrgId" ON public."Sources" USING btree ("OrgId");


--
-- TOC entry 3384 (class 1259 OID 71241)
-- Name: IX_Sources_Title; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sources_Title" ON public."Sources" USING btree ("Title");


--
-- TOC entry 3387 (class 1259 OID 71249)
-- Name: IX_Tags_OrgId_Name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Tags_OrgId_Name" ON public."Tags" USING btree ("OrgId", "Name");


--
-- TOC entry 3404 (class 1259 OID 72821)
-- Name: IX_Towns_Country; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Towns_Country" ON public."Towns" USING btree ("Country");


--
-- TOC entry 3405 (class 1259 OID 72820)
-- Name: IX_Towns_Name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Towns_Name" ON public."Towns" USING btree ("Name");


--
-- TOC entry 3397 (class 1259 OID 72696)
-- Name: IX_TreeInvitations_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TreeInvitations_Email" ON public."TreeInvitations" USING btree ("Email");


--
-- TOC entry 3398 (class 1259 OID 72697)
-- Name: IX_TreeInvitations_Token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TreeInvitations_Token" ON public."TreeInvitations" USING btree ("Token");


--
-- TOC entry 3399 (class 1259 OID 72695)
-- Name: IX_TreeInvitations_TreeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TreeInvitations_TreeId" ON public."TreeInvitations" USING btree ("TreeId");


--
-- TOC entry 3380 (class 1259 OID 71182)
-- Name: IX_UnionMembers_UnionId_PersonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_UnionMembers_UnionId_PersonId" ON public."UnionMembers" USING btree ("UnionId", "PersonId");


--
-- TOC entry 3377 (class 1259 OID 71163)
-- Name: IX_Unions_OrgId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Unions_OrgId" ON public."Unions" USING btree ("OrgId");


--
-- TOC entry 3372 (class 1259 OID 71043)
-- Name: IX_Users_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Email" ON public."Users" USING btree ("Email");


--
-- TOC entry 3392 (class 1259 OID 72482)
-- Name: idx_refreshtoken_value; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_refreshtoken_value ON public."RefreshToken" USING btree ("Value");


--
-- TOC entry 3396 (class 1259 OID 72484)
-- Name: idx_signertoken_value; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_signertoken_value ON public."SignerToken" USING btree ("Value");


--
-- TOC entry 3393 (class 1259 OID 72483)
-- Name: refreshtoken_userid_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX refreshtoken_userid_idx ON public."RefreshToken" USING btree ("UserId");


--
-- TOC entry 3410 (class 2606 OID 71177)
-- Name: UnionMembers FK_UnionMembers_People; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UnionMembers"
    ADD CONSTRAINT "FK_UnionMembers_People" FOREIGN KEY ("PersonId") REFERENCES public."People"("Id") ON DELETE CASCADE;


--
-- TOC entry 3411 (class 2606 OID 71172)
-- Name: UnionMembers FK_UnionMembers_Unions; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UnionMembers"
    ADD CONSTRAINT "FK_UnionMembers_Unions" FOREIGN KEY ("UnionId") REFERENCES public."Unions"("Id") ON DELETE CASCADE;


--
-- TOC entry 3408 (class 2606 OID 71158)
-- Name: Unions FK_Unions_EndPlace; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Unions"
    ADD CONSTRAINT "FK_Unions_EndPlace" FOREIGN KEY ("EndPlaceId") REFERENCES public."Places"("Id") ON DELETE SET NULL;


--
-- TOC entry 3409 (class 2606 OID 71153)
-- Name: Unions FK_Unions_StartPlace; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Unions"
    ADD CONSTRAINT "FK_Unions_StartPlace" FOREIGN KEY ("StartPlaceId") REFERENCES public."Places"("Id") ON DELETE SET NULL;


--
-- TOC entry 3412 (class 2606 OID 72690)
-- Name: TreeInvitations TreeInvitations_AcceptedByUserId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TreeInvitations"
    ADD CONSTRAINT "TreeInvitations_AcceptedByUserId_fkey" FOREIGN KEY ("AcceptedByUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE SET NULL;


--
-- TOC entry 3413 (class 2606 OID 72685)
-- Name: TreeInvitations TreeInvitations_InvitedByUserId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TreeInvitations"
    ADD CONSTRAINT "TreeInvitations_InvitedByUserId_fkey" FOREIGN KEY ("InvitedByUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3414 (class 2606 OID 72680)
-- Name: TreeInvitations TreeInvitations_TreeId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TreeInvitations"
    ADD CONSTRAINT "TreeInvitations_TreeId_fkey" FOREIGN KEY ("TreeId") REFERENCES public."Orgs"("Id") ON DELETE CASCADE;


-- Completed on 2025-12-20 11:26:37

--
-- PostgreSQL database dump complete
--

\unrestrict dq1kpPNIRUsjoaB9IHy2ufESwqdeCEh4WzRYYPeMPIVhQDMCyu7VgnNw0U7dvJ0

