using System.ComponentModel.DataAnnotations;
using FamilyTreeApi.Models.Enums;

namespace FamilyTreeApi.Models;

/// <summary>
/// Platform-level support ticket (no OrgId — not tree-scoped).
/// Any authenticated user can submit; SuperAdmin/Developer can manage.
/// </summary>
public class SupportTicket
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Human-friendly sequential number (auto-generated by DB serial)
    /// </summary>
    public int TicketNumber { get; set; }

    [Required]
    public TicketCategory Category { get; set; } = TicketCategory.Bug;

    public TicketPriority Priority { get; set; } = TicketPriority.Medium;

    [Required]
    public TicketStatus Status { get; set; } = TicketStatus.Open;

    [Required]
    [MaxLength(200)]
    public string Subject { get; set; } = string.Empty;

    [Required]
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Optional steps to reproduce (relevant for bugs)
    /// </summary>
    public string? StepsToReproduce { get; set; }

    /// <summary>
    /// URL/route where the issue occurred (auto-captured from frontend)
    /// </summary>
    [MaxLength(500)]
    public string? PageUrl { get; set; }

    /// <summary>
    /// User-agent string (auto-captured from frontend)
    /// </summary>
    [MaxLength(500)]
    public string? BrowserInfo { get; set; }

    // ---- Submitter ----
    [Required]
    public long SubmittedByUserId { get; set; }
    public ApplicationUser SubmittedByUser { get; set; } = null!;
    public DateTime SubmittedAt { get; set; } = DateTime.UtcNow;

    // ---- Assignment ----
    public long? AssignedToUserId { get; set; }
    public ApplicationUser? AssignedToUser { get; set; }
    public DateTime? AssignedAt { get; set; }

    // ---- Admin Notes (internal, NOT visible to submitter) ----
    public string? AdminNotes { get; set; }

    // ---- Resolution ----
    public DateTime? ResolvedAt { get; set; }
    public long? ResolvedByUserId { get; set; }
    public ApplicationUser? ResolvedByUser { get; set; }
    public string? ResolutionNotes { get; set; }

    // ---- Timestamps ----
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    // ---- Soft delete ----
    public bool IsDeleted { get; set; } = false;
    public DateTime? DeletedAt { get; set; }
    public long? DeletedByUserId { get; set; }

    // ---- Navigation ----
    public ICollection<SupportTicketAttachment> Attachments { get; set; } = new List<SupportTicketAttachment>();
    public ICollection<SupportTicketComment> Comments { get; set; } = new List<SupportTicketComment>();
}
