-- Migration: Create Countries table for nationality lookup
-- This migration adds the Country entity for standardized nationality selection

-- Create the Countries table
CREATE TABLE IF NOT EXISTS "Countries" (
    "Code" character varying(2) NOT NULL,
    "NameEn" character varying(100) NOT NULL,
    "NameAr" character varying(100),
    "NameLocal" character varying(100),
    "Region" character varying(50),
    "IsActive" boolean NOT NULL DEFAULT true,
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Countries" PRIMARY KEY ("Code")
);

-- Create indexes
CREATE INDEX IF NOT EXISTS "IX_Countries_NameEn" ON "Countries" ("NameEn");
CREATE INDEX IF NOT EXISTS "IX_Countries_IsActive" ON "Countries" ("IsActive");
CREATE INDEX IF NOT EXISTS "IX_Countries_Region" ON "Countries" ("Region");

-- Seed data: Insert countries with English and Arabic names
INSERT INTO "Countries" ("Code", "NameEn", "NameAr", "Region", "IsActive", "DisplayOrder")
VALUES
    ('AF', 'Afghanistan', 'أفغانستان', 'Asia', true, 0),
    ('AL', 'Albania', 'ألبانيا', 'Europe', true, 0),
    ('DZ', 'Algeria', 'الجزائر', 'Africa', true, 0),
    ('AD', 'Andorra', 'أندورا', 'Europe', true, 0),
    ('AO', 'Angola', 'أنغولا', 'Africa', true, 0),
    ('AG', 'Antigua and Barbuda', 'أنتيغوا وبربودا', 'Americas', true, 0),
    ('AR', 'Argentina', 'الأرجنتين', 'Americas', true, 0),
    ('AM', 'Armenia', 'أرمينيا', 'Asia', true, 0),
    ('AU', 'Australia', 'أستراليا', 'Oceania', true, 0),
    ('AT', 'Austria', 'النمسا', 'Europe', true, 0),
    ('AZ', 'Azerbaijan', 'أذربيجان', 'Asia', true, 0),
    ('BS', 'Bahamas', 'الباهاما', 'Americas', true, 0),
    ('BH', 'Bahrain', 'البحرين', 'Middle East', true, 0),
    ('BD', 'Bangladesh', 'بنغلاديش', 'Asia', true, 0),
    ('BB', 'Barbados', 'بربادوس', 'Americas', true, 0),
    ('BY', 'Belarus', 'بيلاروسيا', 'Europe', true, 0),
    ('BE', 'Belgium', 'بلجيكا', 'Europe', true, 0),
    ('BZ', 'Belize', 'بليز', 'Americas', true, 0),
    ('BJ', 'Benin', 'بنين', 'Africa', true, 0),
    ('BT', 'Bhutan', 'بوتان', 'Asia', true, 0),
    ('BO', 'Bolivia', 'بوليفيا', 'Americas', true, 0),
    ('BA', 'Bosnia and Herzegovina', 'البوسنة والهرسك', 'Europe', true, 0),
    ('BW', 'Botswana', 'بوتسوانا', 'Africa', true, 0),
    ('BR', 'Brazil', 'البرازيل', 'Americas', true, 0),
    ('BN', 'Brunei', 'بروناي', 'Asia', true, 0),
    ('BG', 'Bulgaria', 'بلغاريا', 'Europe', true, 0),
    ('KH', 'Cambodia', 'كمبوديا', 'Asia', true, 0),
    ('CM', 'Cameroon', 'الكاميرون', 'Africa', true, 0),
    ('CA', 'Canada', 'كندا', 'Americas', true, 0),
    ('CL', 'Chile', 'تشيلي', 'Americas', true, 0),
    ('CN', 'China', 'الصين', 'Asia', true, 0),
    ('CO', 'Colombia', 'كولومبيا', 'Americas', true, 0),
    ('KM', 'Comoros', 'جزر القمر', 'Africa', true, 0),
    ('CR', 'Costa Rica', 'كوستاريكا', 'Americas', true, 0),
    ('HR', 'Croatia', 'كرواتيا', 'Europe', true, 0),
    ('CU', 'Cuba', 'كوبا', 'Americas', true, 0),
    ('CY', 'Cyprus', 'قبرص', 'Europe', true, 0),
    ('CZ', 'Czech Republic', 'التشيك', 'Europe', true, 0),
    ('DK', 'Denmark', 'الدنمارك', 'Europe', true, 0),
    ('DJ', 'Djibouti', 'جيبوتي', 'Africa', true, 0),
    ('DO', 'Dominican Republic', 'جمهورية الدومينيكان', 'Americas', true, 0),
    ('EC', 'Ecuador', 'الإكوادور', 'Americas', true, 0),
    ('EG', 'Egypt', 'مصر', 'Middle East', true, 1),
    ('SV', 'El Salvador', 'السلفادور', 'Americas', true, 0),
    ('ER', 'Eritrea', 'إريتريا', 'Africa', true, 0),
    ('EE', 'Estonia', 'إستونيا', 'Europe', true, 0),
    ('ET', 'Ethiopia', 'إثيوبيا', 'Africa', true, 0),
    ('FI', 'Finland', 'فنلندا', 'Europe', true, 0),
    ('FR', 'France', 'فرنسا', 'Europe', true, 0),
    ('GA', 'Gabon', 'الغابون', 'Africa', true, 0),
    ('GM', 'Gambia', 'غامبيا', 'Africa', true, 0),
    ('GE', 'Georgia', 'جورجيا', 'Asia', true, 0),
    ('DE', 'Germany', 'ألمانيا', 'Europe', true, 0),
    ('GH', 'Ghana', 'غانا', 'Africa', true, 0),
    ('GR', 'Greece', 'اليونان', 'Europe', true, 0),
    ('GT', 'Guatemala', 'غواتيمالا', 'Americas', true, 0),
    ('GN', 'Guinea', 'غينيا', 'Africa', true, 0),
    ('HT', 'Haiti', 'هايتي', 'Americas', true, 0),
    ('HN', 'Honduras', 'هندوراس', 'Americas', true, 0),
    ('HU', 'Hungary', 'المجر', 'Europe', true, 0),
    ('IS', 'Iceland', 'آيسلندا', 'Europe', true, 0),
    ('IN', 'India', 'الهند', 'Asia', true, 0),
    ('ID', 'Indonesia', 'إندونيسيا', 'Asia', true, 0),
    ('IR', 'Iran', 'إيران', 'Middle East', true, 0),
    ('IQ', 'Iraq', 'العراق', 'Middle East', true, 0),
    ('IE', 'Ireland', 'أيرلندا', 'Europe', true, 0),
    ('IL', 'Israel', 'إسرائيل', 'Middle East', true, 0),
    ('IT', 'Italy', 'إيطاليا', 'Europe', true, 0),
    ('JM', 'Jamaica', 'جامايكا', 'Americas', true, 0),
    ('JP', 'Japan', 'اليابان', 'Asia', true, 0),
    ('JO', 'Jordan', 'الأردن', 'Middle East', true, 0),
    ('KZ', 'Kazakhstan', 'كازاخستان', 'Asia', true, 0),
    ('KE', 'Kenya', 'كينيا', 'Africa', true, 0),
    ('KW', 'Kuwait', 'الكويت', 'Middle East', true, 0),
    ('KG', 'Kyrgyzstan', 'قيرغيزستان', 'Asia', true, 0),
    ('LA', 'Laos', 'لاوس', 'Asia', true, 0),
    ('LV', 'Latvia', 'لاتفيا', 'Europe', true, 0),
    ('LB', 'Lebanon', 'لبنان', 'Middle East', true, 0),
    ('LY', 'Libya', 'ليبيا', 'Africa', true, 0),
    ('LT', 'Lithuania', 'ليتوانيا', 'Europe', true, 0),
    ('LU', 'Luxembourg', 'لوكسمبورغ', 'Europe', true, 0),
    ('MK', 'North Macedonia', 'مقدونيا الشمالية', 'Europe', true, 0),
    ('MG', 'Madagascar', 'مدغشقر', 'Africa', true, 0),
    ('MY', 'Malaysia', 'ماليزيا', 'Asia', true, 0),
    ('MV', 'Maldives', 'المالديف', 'Asia', true, 0),
    ('ML', 'Mali', 'مالي', 'Africa', true, 0),
    ('MT', 'Malta', 'مالطا', 'Europe', true, 0),
    ('MR', 'Mauritania', 'موريتانيا', 'Africa', true, 0),
    ('MU', 'Mauritius', 'موريشيوس', 'Africa', true, 0),
    ('MX', 'Mexico', 'المكسيك', 'Americas', true, 0),
    ('MD', 'Moldova', 'مولدوفا', 'Europe', true, 0),
    ('MN', 'Mongolia', 'منغوليا', 'Asia', true, 0),
    ('ME', 'Montenegro', 'الجبل الأسود', 'Europe', true, 0),
    ('MA', 'Morocco', 'المغرب', 'Africa', true, 0),
    ('MZ', 'Mozambique', 'موزمبيق', 'Africa', true, 0),
    ('MM', 'Myanmar', 'ميانمار', 'Asia', true, 0),
    ('NA', 'Namibia', 'ناميبيا', 'Africa', true, 0),
    ('NP', 'Nepal', 'نيبال', 'Asia', true, 0),
    ('NL', 'Netherlands', 'هولندا', 'Europe', true, 0),
    ('NZ', 'New Zealand', 'نيوزيلندا', 'Oceania', true, 0),
    ('NI', 'Nicaragua', 'نيكاراغوا', 'Americas', true, 0),
    ('NE', 'Niger', 'النيجر', 'Africa', true, 0),
    ('NG', 'Nigeria', 'نيجيريا', 'Africa', true, 0),
    ('KP', 'North Korea', 'كوريا الشمالية', 'Asia', true, 0),
    ('NO', 'Norway', 'النرويج', 'Europe', true, 0),
    ('OM', 'Oman', 'عمان', 'Middle East', true, 0),
    ('PK', 'Pakistan', 'باكستان', 'Asia', true, 0),
    ('PS', 'Palestine', 'فلسطين', 'Middle East', true, 0),
    ('PA', 'Panama', 'بنما', 'Americas', true, 0),
    ('PY', 'Paraguay', 'باراغواي', 'Americas', true, 0),
    ('PE', 'Peru', 'بيرو', 'Americas', true, 0),
    ('PH', 'Philippines', 'الفلبين', 'Asia', true, 0),
    ('PL', 'Poland', 'بولندا', 'Europe', true, 0),
    ('PT', 'Portugal', 'البرتغال', 'Europe', true, 0),
    ('QA', 'Qatar', 'قطر', 'Middle East', true, 0),
    ('RO', 'Romania', 'رومانيا', 'Europe', true, 0),
    ('RU', 'Russia', 'روسيا', 'Europe', true, 0),
    ('RW', 'Rwanda', 'رواندا', 'Africa', true, 0),
    ('SA', 'Saudi Arabia', 'السعودية', 'Middle East', true, 0),
    ('SN', 'Senegal', 'السنغال', 'Africa', true, 0),
    ('RS', 'Serbia', 'صربيا', 'Europe', true, 0),
    ('SG', 'Singapore', 'سنغافورة', 'Asia', true, 0),
    ('SK', 'Slovakia', 'سلوفاكيا', 'Europe', true, 0),
    ('SI', 'Slovenia', 'سلوفينيا', 'Europe', true, 0),
    ('SO', 'Somalia', 'الصومال', 'Africa', true, 0),
    ('ZA', 'South Africa', 'جنوب أفريقيا', 'Africa', true, 0),
    ('KR', 'South Korea', 'كوريا الجنوبية', 'Asia', true, 0),
    ('SS', 'South Sudan', 'جنوب السودان', 'Africa', true, 0),
    ('ES', 'Spain', 'إسبانيا', 'Europe', true, 0),
    ('LK', 'Sri Lanka', 'سريلانكا', 'Asia', true, 0),
    ('SD', 'Sudan', 'السودان', 'Africa', true, 1),
    ('SE', 'Sweden', 'السويد', 'Europe', true, 0),
    ('CH', 'Switzerland', 'سويسرا', 'Europe', true, 0),
    ('SY', 'Syria', 'سوريا', 'Middle East', true, 0),
    ('TW', 'Taiwan', 'تايوان', 'Asia', true, 0),
    ('TJ', 'Tajikistan', 'طاجيكستان', 'Asia', true, 0),
    ('TZ', 'Tanzania', 'تنزانيا', 'Africa', true, 0),
    ('TH', 'Thailand', 'تايلاند', 'Asia', true, 0),
    ('TN', 'Tunisia', 'تونس', 'Africa', true, 0),
    ('TR', 'Turkey', 'تركيا', 'Middle East', true, 0),
    ('TM', 'Turkmenistan', 'تركمانستان', 'Asia', true, 0),
    ('UG', 'Uganda', 'أوغندا', 'Africa', true, 0),
    ('UA', 'Ukraine', 'أوكرانيا', 'Europe', true, 0),
    ('AE', 'United Arab Emirates', 'الإمارات', 'Middle East', true, 0),
    ('GB', 'United Kingdom', 'المملكة المتحدة', 'Europe', true, 0),
    ('US', 'United States', 'الولايات المتحدة', 'Americas', true, 0),
    ('UY', 'Uruguay', 'أوروغواي', 'Americas', true, 0),
    ('UZ', 'Uzbekistan', 'أوزبكستان', 'Asia', true, 0),
    ('VE', 'Venezuela', 'فنزويلا', 'Americas', true, 0),
    ('VN', 'Vietnam', 'فيتنام', 'Asia', true, 0),
    ('YE', 'Yemen', 'اليمن', 'Middle East', true, 0),
    ('ZM', 'Zambia', 'زامبيا', 'Africa', true, 0),
    ('ZW', 'Zimbabwe', 'زيمبابوي', 'Africa', true, 0)
ON CONFLICT ("Code") DO NOTHING;

-- Update display order for commonly used countries (Egypt and Sudan first for this app)
UPDATE "Countries" SET "DisplayOrder" = -2 WHERE "Code" = 'EG';
UPDATE "Countries" SET "DisplayOrder" = -1 WHERE "Code" = 'SD';
