-- ============================================================================
-- Migration: Email Verification and Two-Phase Registration
-- Date: 2024-02-03
-- Description: Adds tables for secure email verification and rate limiting
-- ============================================================================

-- Add HomeTownId to AspNetUsers
ALTER TABLE "AspNetUsers"
ADD COLUMN IF NOT EXISTS "HomeTownId" uuid NULL;

-- Add FK constraint if not exists
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'FK_AspNetUsers_HomeTown'
    ) THEN
        ALTER TABLE "AspNetUsers"
        ADD CONSTRAINT "FK_AspNetUsers_HomeTown"
        FOREIGN KEY ("HomeTownId") REFERENCES "Towns"("Id") ON DELETE SET NULL;
    END IF;
END $$;

-- Create index on HomeTownId
CREATE INDEX IF NOT EXISTS "IX_AspNetUsers_HomeTownId" ON "AspNetUsers"("HomeTownId");

-- ============================================================================
-- EmailVerificationCodes Table
-- Stores verification codes for registration and password reset
-- ============================================================================

CREATE TABLE IF NOT EXISTS "EmailVerificationCodes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Email" varchar(256) NOT NULL,
    "UserId" bigint NULL,
    "CodeHash" varchar(64) NOT NULL,
    "Purpose" varchar(20) NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "ExpiresAt" timestamptz NOT NULL,
    "IsUsed" boolean NOT NULL DEFAULT false,
    "UsedAt" timestamptz NULL,
    "AttemptCount" integer NOT NULL DEFAULT 0,
    "IpAddress" varchar(45) NULL,
    CONSTRAINT "FK_EmailVerificationCodes_User" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE
);

-- Indexes for EmailVerificationCodes
CREATE INDEX IF NOT EXISTS "IX_EmailVerificationCodes_Email_Purpose"
    ON "EmailVerificationCodes"("Email", "Purpose");
CREATE INDEX IF NOT EXISTS "IX_EmailVerificationCodes_ExpiresAt"
    ON "EmailVerificationCodes"("ExpiresAt");
CREATE INDEX IF NOT EXISTS "IX_EmailVerificationCodes_CreatedAt"
    ON "EmailVerificationCodes"("CreatedAt");

-- ============================================================================
-- RegistrationTokens Table
-- Stores encrypted registration data with secure random tokens
-- SECURITY: Token is cryptographically random, data is AES encrypted
-- ============================================================================

CREATE TABLE IF NOT EXISTS "RegistrationTokens" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Token" varchar(128) NOT NULL,
    "Email" varchar(256) NOT NULL,
    "EncryptedData" bytea NOT NULL,
    "IV" bytea NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "ExpiresAt" timestamptz NOT NULL,
    "IsUsed" boolean NOT NULL DEFAULT false,
    "UsedAt" timestamptz NULL,
    "IpAddress" varchar(45) NULL
);

-- Token must be unique (it's our lookup key)
CREATE UNIQUE INDEX IF NOT EXISTS "IX_RegistrationTokens_Token"
    ON "RegistrationTokens"("Token");
CREATE INDEX IF NOT EXISTS "IX_RegistrationTokens_Email"
    ON "RegistrationTokens"("Email");
CREATE INDEX IF NOT EXISTS "IX_RegistrationTokens_ExpiresAt"
    ON "RegistrationTokens"("ExpiresAt");

-- ============================================================================
-- Cleanup Job (Optional - can use pg_cron or application background service)
-- Deletes expired records older than 24 hours
-- ============================================================================

-- Create a function to clean up expired records
CREATE OR REPLACE FUNCTION cleanup_expired_verification_data()
RETURNS void AS $$
BEGIN
    -- Delete expired verification codes older than 24 hours
    DELETE FROM "EmailVerificationCodes"
    WHERE "ExpiresAt" < now() - INTERVAL '24 hours';

    -- Delete expired registration tokens older than 24 hours
    DELETE FROM "RegistrationTokens"
    WHERE "ExpiresAt" < now() - INTERVAL '24 hours';
END;
$$ LANGUAGE plpgsql;

-- Optional: Schedule with pg_cron (if available)
-- SELECT cron.schedule('cleanup-verification', '0 * * * *', 'SELECT cleanup_expired_verification_data();');

-- ============================================================================
-- Verification Query Examples
-- ============================================================================

-- Example: Find valid verification code
-- SELECT * FROM "EmailVerificationCodes"
-- WHERE "Email" = 'user@example.com'
--   AND "Purpose" = 'Registration'
--   AND "IsUsed" = false
--   AND "ExpiresAt" > now()
-- ORDER BY "CreatedAt" DESC
-- LIMIT 1;

-- Example: Find registration token
-- SELECT * FROM "RegistrationTokens"
-- WHERE "Token" = 'abc123...'
--   AND "IsUsed" = false
--   AND "ExpiresAt" > now();
